/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.Answer;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerRecord extends org.jooq.impl.UpdatableRecordImpl<AnswerRecord> implements org.jooq.Record3<Integer, String, Integer> {

	private static final long serialVersionUID = 1241381638;

	/**
	 * Setter for <code>public.answer.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.answer.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.answer.text</code>.
	 */
	public void setText(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.answer.text</code>.
	 */
	public String getText() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.answer.question_id</code>.
	 */
	public void setQuestionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.answer.question_id</code>.
	 */
	public Integer getQuestionId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return Answer.ANSWER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return Answer.ANSWER.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return Answer.ANSWER.QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value2(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value3(Integer value) {
		setQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord values(Integer value1, String value2, Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnswerRecord
	 */
	public AnswerRecord() {
		super(Answer.ANSWER);
	}

	/**
	 * Create a detached, initialised AnswerRecord
	 */
	public AnswerRecord(Integer id, String text, Integer questionId) {
		super(Answer.ANSWER);

		setValue(0, id);
		setValue(1, text);
		setValue(2, questionId);
	}
}
