/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.EduGroup;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroupRecord extends org.jooq.impl.UpdatableRecordImpl<EduGroupRecord> implements org.jooq.Record3<Integer, String, String> {

	private static final long serialVersionUID = 1490172681;

	/**
	 * Setter for <code>public.edu_group.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.edu_group.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.edu_group.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.edu_group.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.edu_group.instructor</code>.
	 */
	public void setInstructor(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.edu_group.instructor</code>.
	 */
	public String getInstructor() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return EduGroup.EDU_GROUP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return EduGroup.EDU_GROUP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return EduGroup.EDU_GROUP.INSTRUCTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getInstructor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupRecord value3(String value) {
		setInstructor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupRecord values(Integer value1, String value2, String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EduGroupRecord
	 */
	public EduGroupRecord() {
		super(EduGroup.EDU_GROUP);
	}

	/**
	 * Create a detached, initialised EduGroupRecord
	 */
	public EduGroupRecord(Integer id, String name, String instructor) {
		super(EduGroup.EDU_GROUP);

		setValue(0, id);
		setValue(1, name);
		setValue(2, instructor);
	}
}
