/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.EduGroupCourse;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroupCourseRecord extends org.jooq.impl.UpdatableRecordImpl<EduGroupCourseRecord> implements org.jooq.Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = -375878889;

	/**
	 * Setter for <code>public.edu_group_course.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.edu_group_course.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.edu_group_course.edu_group_id</code>.
	 */
	public void setEduGroupId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.edu_group_course.edu_group_id</code>.
	 */
	public Integer getEduGroupId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.edu_group_course.studies_course_id</code>.
	 */
	public void setStudiesCourseId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.edu_group_course.studies_course_id</code>.
	 */
	public Integer getStudiesCourseId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return EduGroupCourse.EDU_GROUP_COURSE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return EduGroupCourse.EDU_GROUP_COURSE.EDU_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return EduGroupCourse.EDU_GROUP_COURSE.STUDIES_COURSE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getEduGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getStudiesCourseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupCourseRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupCourseRecord value2(Integer value) {
		setEduGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupCourseRecord value3(Integer value) {
		setStudiesCourseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroupCourseRecord values(Integer value1, Integer value2, Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EduGroupCourseRecord
	 */
	public EduGroupCourseRecord() {
		super(EduGroupCourse.EDU_GROUP_COURSE);
	}

	/**
	 * Create a detached, initialised EduGroupCourseRecord
	 */
	public EduGroupCourseRecord(Integer id, Integer eduGroupId, Integer studiesCourseId) {
		super(EduGroupCourse.EDU_GROUP_COURSE);

		setValue(0, id);
		setValue(1, eduGroupId);
		setValue(2, studiesCourseId);
	}
}
