/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.ExamRule;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamRuleRecord extends org.jooq.impl.UpdatableRecordImpl<ExamRuleRecord> implements org.jooq.Record3<Integer, String, Integer> {

	private static final long serialVersionUID = 2072094607;

	/**
	 * Setter for <code>public.exam_rule.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.exam_rule.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.exam_rule.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.exam_rule.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.exam_rule.num_questions</code>.
	 */
	public void setNumQuestions(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.exam_rule.num_questions</code>.
	 */
	public Integer getNumQuestions() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, String, Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return ExamRule.EXAM_RULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return ExamRule.EXAM_RULE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return ExamRule.EXAM_RULE.NUM_QUESTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNumQuestions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamRuleRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamRuleRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamRuleRecord value3(Integer value) {
		setNumQuestions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamRuleRecord values(Integer value1, String value2, Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExamRuleRecord
	 */
	public ExamRuleRecord() {
		super(ExamRule.EXAM_RULE);
	}

	/**
	 * Create a detached, initialised ExamRuleRecord
	 */
	public ExamRuleRecord(Integer id, String name, Integer numQuestions) {
		super(ExamRule.EXAM_RULE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, numQuestions);
	}
}
