/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.RolePrivs;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivsRecord extends org.jooq.impl.UpdatableRecordImpl<RolePrivsRecord> implements org.jooq.Record2<String, String> {

	private static final long serialVersionUID = -1197601775;

	/**
	 * Setter for <code>public.role_privs.rolename</code>.
	 */
	public void setRolename(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.role_privs.rolename</code>.
	 */
	public String getRolename() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.role_privs.privilege_id</code>.
	 */
	public void setPrivilegeId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.role_privs.privilege_id</code>.
	 */
	public String getPrivilegeId() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<String, String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<String, String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<String, String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return RolePrivs.ROLE_PRIVS.ROLENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return RolePrivs.ROLE_PRIVS.PRIVILEGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getRolename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPrivilegeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolePrivsRecord value1(String value) {
		setRolename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolePrivsRecord value2(String value) {
		setPrivilegeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolePrivsRecord values(String value1, String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RolePrivsRecord
	 */
	public RolePrivsRecord() {
		super(RolePrivs.ROLE_PRIVS);
	}

	/**
	 * Create a detached, initialised RolePrivsRecord
	 */
	public RolePrivsRecord(String rolename, String privilegeId) {
		super(RolePrivs.ROLE_PRIVS);

		setValue(0, rolename);
		setValue(1, privilegeId);
	}
}
