/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.StudentTask;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentTaskRecord extends org.jooq.impl.UpdatableRecordImpl<StudentTaskRecord> implements org.jooq.Record5<Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -2059245541;

	/**
	 * Setter for <code>public.student_task.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student_task.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student_task.student_id</code>.
	 */
	public void setStudentId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student_task.student_id</code>.
	 */
	public Integer getStudentId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.student_task.exam_id</code>.
	 */
	public void setExamId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student_task.exam_id</code>.
	 */
	public Integer getExamId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.student_task.examination_ticket_id</code>.
	 */
	public void setExaminationTicketId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student_task.examination_ticket_id</code>.
	 */
	public Integer getExaminationTicketId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.student_task.student_result_id</code>.
	 */
	public void setStudentResultId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student_task.student_result_id</code>.
	 */
	public Integer getStudentResultId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return StudentTask.STUDENT_TASK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return StudentTask.STUDENT_TASK.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return StudentTask.STUDENT_TASK.EXAM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field4() {
		return StudentTask.STUDENT_TASK.EXAMINATION_TICKET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field5() {
		return StudentTask.STUDENT_TASK.STUDENT_RESULT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getExamId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getExaminationTicketId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getStudentResultId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord value2(Integer value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord value3(Integer value) {
		setExamId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord value4(Integer value) {
		setExaminationTicketId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord value5(Integer value) {
		setStudentResultId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentTaskRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentTaskRecord
	 */
	public StudentTaskRecord() {
		super(StudentTask.STUDENT_TASK);
	}

	/**
	 * Create a detached, initialised StudentTaskRecord
	 */
	public StudentTaskRecord(Integer id, Integer studentId, Integer examId, Integer examinationTicketId, Integer studentResultId) {
		super(StudentTask.STUDENT_TASK);

		setValue(0, id);
		setValue(1, studentId);
		setValue(2, examId);
		setValue(3, examinationTicketId);
		setValue(4, studentResultId);
	}
}
