/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.StudentResult;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentResultRecord extends org.jooq.impl.UpdatableRecordImpl<StudentResultRecord> implements org.jooq.Record7<Integer, String, Integer, Integer, Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -1809882372;

	/**
	 * Setter for <code>public.student_result.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student_result.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student_result.text</code>.
	 */
	public void setText(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student_result.text</code>.
	 */
	public String getText() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.student_result.ball</code>.
	 */
	public void setBall(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student_result.ball</code>.
	 */
	public Integer getBall() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.student_result.success_question</code>.
	 */
	public void setSuccessQuestion(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student_result.success_question</code>.
	 */
	public Integer getSuccessQuestion() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.student_result.all_questions</code>.
	 */
	public void setAllQuestions(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student_result.all_questions</code>.
	 */
	public Integer getAllQuestions() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.student_result.time_start</code>.
	 */
	public void setTimeStart(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.student_result.time_start</code>.
	 */
	public java.sql.Timestamp getTimeStart() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.student_result.time_end</code>.
	 */
	public void setTimeEnd(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.student_result.time_end</code>.
	 */
	public java.sql.Timestamp getTimeEnd() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<Integer, String, Integer, Integer, Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<Integer, String, Integer, Integer, Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return StudentResult.STUDENT_RESULT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return StudentResult.STUDENT_RESULT.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return StudentResult.STUDENT_RESULT.BALL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field4() {
		return StudentResult.STUDENT_RESULT.SUCCESS_QUESTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field5() {
		return StudentResult.STUDENT_RESULT.ALL_QUESTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return StudentResult.STUDENT_RESULT.TIME_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return StudentResult.STUDENT_RESULT.TIME_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getBall();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSuccessQuestion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAllQuestions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getTimeStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getTimeEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value2(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value3(Integer value) {
		setBall(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value4(Integer value) {
		setSuccessQuestion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value5(Integer value) {
		setAllQuestions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value6(java.sql.Timestamp value) {
		setTimeStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord value7(java.sql.Timestamp value) {
		setTimeEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResultRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentResultRecord
	 */
	public StudentResultRecord() {
		super(StudentResult.STUDENT_RESULT);
	}

	/**
	 * Create a detached, initialised StudentResultRecord
	 */
	public StudentResultRecord(Integer id, String text, Integer ball, Integer successQuestion, Integer allQuestions, java.sql.Timestamp timeStart, java.sql.Timestamp timeEnd) {
		super(StudentResult.STUDENT_RESULT);

		setValue(0, id);
		setValue(1, text);
		setValue(2, ball);
		setValue(3, successQuestion);
		setValue(4, allQuestions);
		setValue(5, timeStart);
		setValue(6, timeEnd);
	}
}
