/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.Student;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends org.jooq.impl.UpdatableRecordImpl<StudentRecord> implements org.jooq.Record5<Integer, String, String, String, Integer> {

	private static final long serialVersionUID = -1604097118;

	/**
	 * Setter for <code>public.student.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.student.full_name</code>.
	 */
	public void setFullName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student.full_name</code>.
	 */
	public String getFullName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.student.username</code>.
	 */
	public void setUsername(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student.username</code>.
	 */
	public String getUsername() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.student.edu_group_id</code>.
	 */
	public void setEduGroupId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student.edu_group_id</code>.
	 */
	public Integer getEduGroupId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<Integer, String, String, String, Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<Integer, String, String, String, Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return Student.STUDENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return Student.STUDENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return Student.STUDENT.FULL_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field4() {
		return Student.STUDENT.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field5() {
		return Student.STUDENT.EDU_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFullName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getEduGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value3(String value) {
		setFullName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value4(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value5(Integer value) {
		setEduGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentRecord
	 */
	public StudentRecord() {
		super(Student.STUDENT);
	}

	/**
	 * Create a detached, initialised StudentRecord
	 */
	public StudentRecord(Integer id, String name, String fullName, String username, Integer eduGroupId) {
		super(Student.STUDENT);

		setValue(0, id);
		setValue(1, name);
		setValue(2, fullName);
		setValue(3, username);
		setValue(4, eduGroupId);
	}
}
