/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.TaskQuestions;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskQuestionsRecord extends org.jooq.impl.UpdatableRecordImpl<TaskQuestionsRecord> implements org.jooq.Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = -1649818272;

	/**
	 * Setter for <code>public.task_questions.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.task_questions.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.task_questions.student_task_id</code>.
	 */
	public void setStudentTaskId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.task_questions.student_task_id</code>.
	 */
	public Integer getStudentTaskId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.task_questions.question_id</code>.
	 */
	public void setQuestionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.task_questions.question_id</code>.
	 */
	public Integer getQuestionId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return TaskQuestions.TASK_QUESTIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return TaskQuestions.TASK_QUESTIONS.STUDENT_TASK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return TaskQuestions.TASK_QUESTIONS.QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStudentTaskId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskQuestionsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskQuestionsRecord value2(Integer value) {
		setStudentTaskId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskQuestionsRecord value3(Integer value) {
		setQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskQuestionsRecord values(Integer value1, Integer value2, Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TaskQuestionsRecord
	 */
	public TaskQuestionsRecord() {
		super(TaskQuestions.TASK_QUESTIONS);
	}

	/**
	 * Create a detached, initialised TaskQuestionsRecord
	 */
	public TaskQuestionsRecord(Integer id, Integer studentTaskId, Integer questionId) {
		super(TaskQuestions.TASK_QUESTIONS);

		setValue(0, id);
		setValue(1, studentTaskId);
		setValue(2, questionId);
	}
}
