/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.Theme;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThemeRecord extends org.jooq.impl.UpdatableRecordImpl<ThemeRecord> implements org.jooq.Record6<Integer, Integer, String, String, Integer, Integer> {

	private static final long serialVersionUID = -419770747;

	/**
	 * Setter for <code>public.theme.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.theme.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.theme.parent</code>.
	 */
	public void setParent(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.theme.parent</code>.
	 */
	public Integer getParent() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.theme.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.theme.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.theme.creator_name</code>.
	 */
	public void setCreatorName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.theme.creator_name</code>.
	 */
	public String getCreatorName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.theme.rgt</code>.
	 */
	public void setRgt(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.theme.rgt</code>.
	 */
	public Integer getRgt() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.theme.lft</code>.
	 */
	public void setLft(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.theme.lft</code>.
	 */
	public Integer getLft() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<Integer, Integer, String, String, Integer, Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<Integer, Integer, String, String, Integer, Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return Theme.THEME.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return Theme.THEME.PARENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return Theme.THEME.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field4() {
		return Theme.THEME.CREATOR_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field5() {
		return Theme.THEME.RGT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field6() {
		return Theme.THEME.LFT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getParent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCreatorName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getRgt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getLft();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value2(Integer value) {
		setParent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value4(String value) {
		setCreatorName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value5(Integer value) {
		setRgt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord value6(Integer value) {
		setLft(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThemeRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ThemeRecord
	 */
	public ThemeRecord() {
		super(Theme.THEME);
	}

	/**
	 * Create a detached, initialised ThemeRecord
	 */
	public ThemeRecord(Integer id, Integer parent, String name, String creatorName, Integer rgt, Integer lft) {
		super(Theme.THEME);

		setValue(0, id);
		setValue(1, parent);
		setValue(2, name);
		setValue(3, creatorName);
		setValue(4, rgt);
		setValue(5, lft);
	}
}
