/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.records;

import ua.org.pius.studtrain.db.tables.Users;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<UsersRecord> implements org.jooq.Record10<String, java.sql.Timestamp, String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -1705358710;

	/**
	 * Setter for <code>public.users.username</code>.
	 */
	public void setUsername(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users.username</code>.
	 */
	public String getUsername() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.users.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.users.activation</code>.
	 */
	public void setActivation(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users.activation</code>.
	 */
	public String getActivation() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.users.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.users.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.users.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.users.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.users.gender</code>.
	 */
	public void setGender(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.users.gender</code>.
	 */
	public String getGender() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.users.email</code>.
	 */
	public void setEmail(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.users.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.users.phone</code>.
	 */
	public void setPhone(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.users.phone</code>.
	 */
	public String getPhone() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.users.activation_key</code>.
	 */
	public void setActivationKey(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.users.activation_key</code>.
	 */
	public String getActivationKey() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.users.params</code>.
	 */
	public void setParams(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.users.params</code>.
	 */
	public String getParams() {
		return (String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<String, java.sql.Timestamp, String, String, String, String, String, String, String, String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<String, java.sql.Timestamp, String, String, String, String, String, String, String, String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return Users.USERS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return Users.USERS.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return Users.USERS.ACTIVATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field4() {
		return Users.USERS.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field5() {
		return Users.USERS.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field6() {
		return Users.USERS.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field7() {
		return Users.USERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field8() {
		return Users.USERS.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field9() {
		return Users.USERS.ACTIVATION_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field10() {
		return Users.USERS.PARAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getActivation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getActivationKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getParams();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(String value) {
		setActivation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value5(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value6(String value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value7(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value8(String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value9(String value) {
		setActivationKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value10(String value) {
		setParams(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(String value1, java.sql.Timestamp value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(String username, java.sql.Timestamp createdAt, String activation, String firstName, String lastName, String gender, String email, String phone, String activationKey, String params) {
		super(Users.USERS);

		setValue(0, username);
		setValue(1, createdAt);
		setValue(2, activation);
		setValue(3, firstName);
		setValue(4, lastName);
		setValue(5, gender);
		setValue(6, email);
		setValue(7, phone);
		setValue(8, activationKey);
		setValue(9, params);
	}
}
