/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.AnswerRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answer extends org.jooq.impl.TableImpl<AnswerRecord> {

	private static final long serialVersionUID = -1895950180;

	/**
	 * The singleton instance of <code>public.answer</code>
	 */
	public static final Answer ANSWER = new Answer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnswerRecord> getRecordType() {
		return AnswerRecord.class;
	}

	/**
	 * The column <code>public.answer.id</code>.
	 */
	public final org.jooq.TableField<AnswerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.answer.text</code>.
	 */
	public final org.jooq.TableField<AnswerRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.answer.question_id</code>.
	 */
	public final org.jooq.TableField<AnswerRecord, Integer> QUESTION_ID = createField("question_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.answer</code> table reference
	 */
	public Answer() {
		this("answer", null);
	}

	/**
	 * Create an aliased <code>public.answer</code> table reference
	 */
	public Answer(String alias) {
		this(alias, Answer.ANSWER);
	}

	private Answer(String alias, org.jooq.Table<AnswerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Answer(String alias, org.jooq.Table<AnswerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AnswerRecord> getPrimaryKey() {
		return Keys.PK_ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AnswerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AnswerRecord>>asList(Keys.PK_ANSWER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AnswerRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AnswerRecord, ?>>asList(Keys.ANSWER__FK_ANSWER_QUESTION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Answer as(String alias) {
		return new Answer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Answer rename(String name) {
		return new Answer(name, null);
	}
}
