/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.EduGroupRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroup extends org.jooq.impl.TableImpl<EduGroupRecord> {

	private static final long serialVersionUID = -1260304265;

	/**
	 * The singleton instance of <code>public.edu_group</code>
	 */
	public static final EduGroup EDU_GROUP = new EduGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EduGroupRecord> getRecordType() {
		return EduGroupRecord.class;
	}

	/**
	 * The column <code>public.edu_group.id</code>.
	 */
	public final org.jooq.TableField<EduGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.edu_group.name</code>.
	 */
	public final org.jooq.TableField<EduGroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>public.edu_group.instructor</code>.
	 */
	public final org.jooq.TableField<EduGroupRecord, String> INSTRUCTOR = createField("instructor", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * Create a <code>public.edu_group</code> table reference
	 */
	public EduGroup() {
		this("edu_group", null);
	}

	/**
	 * Create an aliased <code>public.edu_group</code> table reference
	 */
	public EduGroup(String alias) {
		this(alias, EduGroup.EDU_GROUP);
	}

	private EduGroup(String alias, org.jooq.Table<EduGroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private EduGroup(String alias, org.jooq.Table<EduGroupRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<EduGroupRecord> getPrimaryKey() {
		return Keys.PK_EDU_GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<EduGroupRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<EduGroupRecord>>asList(Keys.PK_EDU_GROUP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<EduGroupRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<EduGroupRecord, ?>>asList(Keys.EDU_GROUP__FK_EDU_GROUP_USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduGroup as(String alias) {
		return new EduGroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EduGroup rename(String name) {
		return new EduGroup(name, null);
	}
}
