/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.ExamTreeNodeRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamTreeNode extends org.jooq.impl.TableImpl<ExamTreeNodeRecord> {

	private static final long serialVersionUID = 553567745;

	/**
	 * The singleton instance of <code>public.exam_tree_node</code>
	 */
	public static final ExamTreeNode EXAM_TREE_NODE = new ExamTreeNode();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExamTreeNodeRecord> getRecordType() {
		return ExamTreeNodeRecord.class;
	}

	/**
	 * The column <code>public.exam_tree_node.id</code>.
	 */
	public final org.jooq.TableField<ExamTreeNodeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.exam_tree_node.exam_id</code>.
	 */
	public final org.jooq.TableField<ExamTreeNodeRecord, Integer> EXAM_ID = createField("exam_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.exam_tree_node.theme_id</code>.
	 */
	public final org.jooq.TableField<ExamTreeNodeRecord, Integer> THEME_ID = createField("theme_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.exam_tree_node.exam_rule_id</code>.
	 */
	public final org.jooq.TableField<ExamTreeNodeRecord, Integer> EXAM_RULE_ID = createField("exam_rule_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.exam_tree_node</code> table reference
	 */
	public ExamTreeNode() {
		this("exam_tree_node", null);
	}

	/**
	 * Create an aliased <code>public.exam_tree_node</code> table reference
	 */
	public ExamTreeNode(String alias) {
		this(alias, ExamTreeNode.EXAM_TREE_NODE);
	}

	private ExamTreeNode(String alias, org.jooq.Table<ExamTreeNodeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExamTreeNode(String alias, org.jooq.Table<ExamTreeNodeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ExamTreeNodeRecord> getPrimaryKey() {
		return Keys.PK_EXAM_TREE_NODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ExamTreeNodeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ExamTreeNodeRecord>>asList(Keys.PK_EXAM_TREE_NODE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ExamTreeNodeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ExamTreeNodeRecord, ?>>asList(Keys.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM, Keys.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_THEME, Keys.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM_RULE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamTreeNode as(String alias) {
		return new ExamTreeNode(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ExamTreeNode rename(String name) {
		return new ExamTreeNode(name, null);
	}
}
