/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.ExamRuleRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamRule extends org.jooq.impl.TableImpl<ExamRuleRecord> {

	private static final long serialVersionUID = 1721057420;

	/**
	 * The singleton instance of <code>public.exam_rule</code>
	 */
	public static final ExamRule EXAM_RULE = new ExamRule();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExamRuleRecord> getRecordType() {
		return ExamRuleRecord.class;
	}

	/**
	 * The column <code>public.exam_rule.id</code>.
	 */
	public final org.jooq.TableField<ExamRuleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.exam_rule.name</code>.
	 */
	public final org.jooq.TableField<ExamRuleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>public.exam_rule.num_questions</code>.
	 */
	public final org.jooq.TableField<ExamRuleRecord, Integer> NUM_QUESTIONS = createField("num_questions", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.exam_rule</code> table reference
	 */
	public ExamRule() {
		this("exam_rule", null);
	}

	/**
	 * Create an aliased <code>public.exam_rule</code> table reference
	 */
	public ExamRule(String alias) {
		this(alias, ExamRule.EXAM_RULE);
	}

	private ExamRule(String alias, org.jooq.Table<ExamRuleRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExamRule(String alias, org.jooq.Table<ExamRuleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ExamRuleRecord> getPrimaryKey() {
		return Keys.PK_EXAM_RULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ExamRuleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ExamRuleRecord>>asList(Keys.PK_EXAM_RULE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamRule as(String alias) {
		return new ExamRule(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ExamRule rename(String name) {
		return new ExamRule(name, null);
	}
}
