/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.PrivsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Privs extends org.jooq.impl.TableImpl<PrivsRecord> {

	private static final long serialVersionUID = 1117916114;

	/**
	 * The singleton instance of <code>public.privs</code>
	 */
	public static final Privs PRIVS = new Privs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrivsRecord> getRecordType() {
		return PrivsRecord.class;
	}

	/**
	 * The column <code>public.privs.id</code>.
	 */
	public final org.jooq.TableField<PrivsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

	/**
	 * The column <code>public.privs.name</code>.
	 */
	public final org.jooq.TableField<PrivsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.privs.description</code>.
	 */
	public final org.jooq.TableField<PrivsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * Create a <code>public.privs</code> table reference
	 */
	public Privs() {
		this("privs", null);
	}

	/**
	 * Create an aliased <code>public.privs</code> table reference
	 */
	public Privs(String alias) {
		this(alias, Privs.PRIVS);
	}

	private Privs(String alias, org.jooq.Table<PrivsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Privs(String alias, org.jooq.Table<PrivsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<PrivsRecord> getPrimaryKey() {
		return Keys.PK_PRIVS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<PrivsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<PrivsRecord>>asList(Keys.PK_PRIVS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Privs as(String alias) {
		return new Privs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Privs rename(String name) {
		return new Privs(name, null);
	}
}
