/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.QuestionStatisticsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionStatistics extends org.jooq.impl.TableImpl<QuestionStatisticsRecord> {

	private static final long serialVersionUID = -1979241377;

	/**
	 * The singleton instance of <code>public.question_statistics</code>
	 */
	public static final QuestionStatistics QUESTION_STATISTICS = new QuestionStatistics();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<QuestionStatisticsRecord> getRecordType() {
		return QuestionStatisticsRecord.class;
	}

	/**
	 * The column <code>public.question_statistics.id</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.question_statistics.number_exam_for_theme</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_EXAM_FOR_THEME = createField("number_exam_for_theme", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.number_exam_for_question</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_EXAM_FOR_QUESTION = createField("number_exam_for_question", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.number_corrects</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_CORRECTS = createField("number_corrects", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.number_incorrects</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_INCORRECTS = createField("number_incorrects", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.number_rejections</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_REJECTIONS = createField("number_rejections", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.number_timeout</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> NUMBER_TIMEOUT = createField("number_timeout", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.summ_ball_possible</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> SUMM_BALL_POSSIBLE = createField("summ_ball_possible", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.summ_ball</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> SUMM_BALL = createField("summ_ball", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.question_statistics.question_id</code>.
	 */
	public final org.jooq.TableField<QuestionStatisticsRecord, Integer> QUESTION_ID = createField("question_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.question_statistics</code> table reference
	 */
	public QuestionStatistics() {
		this("question_statistics", null);
	}

	/**
	 * Create an aliased <code>public.question_statistics</code> table reference
	 */
	public QuestionStatistics(String alias) {
		this(alias, QuestionStatistics.QUESTION_STATISTICS);
	}

	private QuestionStatistics(String alias, org.jooq.Table<QuestionStatisticsRecord> aliased) {
		this(alias, aliased, null);
	}

	private QuestionStatistics(String alias, org.jooq.Table<QuestionStatisticsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<QuestionStatisticsRecord> getPrimaryKey() {
		return Keys.PK_QUESTION_STATISTICS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<QuestionStatisticsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<QuestionStatisticsRecord>>asList(Keys.PK_QUESTION_STATISTICS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<QuestionStatisticsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<QuestionStatisticsRecord, ?>>asList(Keys.QUESTION_STATISTICS__FK_QUESTION_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionStatistics as(String alias) {
		return new QuestionStatistics(alias, this);
	}

	/**
	 * Rename this table
	 */
	public QuestionStatistics rename(String name) {
		return new QuestionStatistics(name, null);
	}
}
