/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.RolePrivsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivs extends org.jooq.impl.TableImpl<RolePrivsRecord> {

	private static final long serialVersionUID = 18775104;

	/**
	 * The singleton instance of <code>public.role_privs</code>
	 */
	public static final RolePrivs ROLE_PRIVS = new RolePrivs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RolePrivsRecord> getRecordType() {
		return RolePrivsRecord.class;
	}

	/**
	 * The column <code>public.role_privs.rolename</code>.
	 */
	public final org.jooq.TableField<RolePrivsRecord, String> ROLENAME = createField("rolename", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.role_privs.privilege_id</code>.
	 */
	public final org.jooq.TableField<RolePrivsRecord, String> PRIVILEGE_ID = createField("privilege_id", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

	/**
	 * Create a <code>public.role_privs</code> table reference
	 */
	public RolePrivs() {
		this("role_privs", null);
	}

	/**
	 * Create an aliased <code>public.role_privs</code> table reference
	 */
	public RolePrivs(String alias) {
		this(alias, RolePrivs.ROLE_PRIVS);
	}

	private RolePrivs(String alias, org.jooq.Table<RolePrivsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RolePrivs(String alias, org.jooq.Table<RolePrivsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<RolePrivsRecord> getPrimaryKey() {
		return Keys.PK_ROLE_PRIVS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<RolePrivsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<RolePrivsRecord>>asList(Keys.PK_ROLE_PRIVS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<RolePrivsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<RolePrivsRecord, ?>>asList(Keys.ROLE_PRIVS__FK_ROLE_PRIVS_ROLES, Keys.ROLE_PRIVS__FK_ROLE_PRIVS_PRIVS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolePrivs as(String alias) {
		return new RolePrivs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RolePrivs rename(String name) {
		return new RolePrivs(name, null);
	}
}
