/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.RolesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends org.jooq.impl.TableImpl<RolesRecord> {

	private static final long serialVersionUID = -1480241090;

	/**
	 * The singleton instance of <code>public.roles</code>
	 */
	public static final Roles ROLES = new Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RolesRecord> getRecordType() {
		return RolesRecord.class;
	}

	/**
	 * The column <code>public.roles.rolename</code>.
	 */
	public final org.jooq.TableField<RolesRecord, String> ROLENAME = createField("rolename", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.roles.created_at</code>.
	 */
	public final org.jooq.TableField<RolesRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.roles.printname</code>.
	 */
	public final org.jooq.TableField<RolesRecord, String> PRINTNAME = createField("printname", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * Create a <code>public.roles</code> table reference
	 */
	public Roles() {
		this("roles", null);
	}

	/**
	 * Create an aliased <code>public.roles</code> table reference
	 */
	public Roles(String alias) {
		this(alias, Roles.ROLES);
	}

	private Roles(String alias, org.jooq.Table<RolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Roles(String alias, org.jooq.Table<RolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<RolesRecord> getPrimaryKey() {
		return Keys.PK_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<RolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<RolesRecord>>asList(Keys.PK_ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Roles as(String alias) {
		return new Roles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Roles rename(String name) {
		return new Roles(name, null);
	}
}
