/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.StudentStatisticsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentStatistics extends org.jooq.impl.TableImpl<StudentStatisticsRecord> {

	private static final long serialVersionUID = -1625700388;

	/**
	 * The singleton instance of <code>public.student_statistics</code>
	 */
	public static final StudentStatistics STUDENT_STATISTICS = new StudentStatistics();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudentStatisticsRecord> getRecordType() {
		return StudentStatisticsRecord.class;
	}

	/**
	 * The column <code>public.student_statistics.id</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.student_statistics.number_exam_for_group</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_EXAM_FOR_GROUP = createField("number_exam_for_group", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.number_exam_for_stud</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_EXAM_FOR_STUD = createField("number_exam_for_stud", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.number_corrects</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_CORRECTS = createField("number_corrects", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.number_incorrects</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_INCORRECTS = createField("number_incorrects", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.number_rejections</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_REJECTIONS = createField("number_rejections", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.number_timeout</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> NUMBER_TIMEOUT = createField("number_timeout", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.summ_ball_possible</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> SUMM_BALL_POSSIBLE = createField("summ_ball_possible", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.summ_ball</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> SUMM_BALL = createField("summ_ball", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_statistics.student_id</code>.
	 */
	public final org.jooq.TableField<StudentStatisticsRecord, Integer> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.student_statistics</code> table reference
	 */
	public StudentStatistics() {
		this("student_statistics", null);
	}

	/**
	 * Create an aliased <code>public.student_statistics</code> table reference
	 */
	public StudentStatistics(String alias) {
		this(alias, StudentStatistics.STUDENT_STATISTICS);
	}

	private StudentStatistics(String alias, org.jooq.Table<StudentStatisticsRecord> aliased) {
		this(alias, aliased, null);
	}

	private StudentStatistics(String alias, org.jooq.Table<StudentStatisticsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<StudentStatisticsRecord> getPrimaryKey() {
		return Keys.PK_STUDENT_STATISTICS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<StudentStatisticsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<StudentStatisticsRecord>>asList(Keys.PK_STUDENT_STATISTICS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<StudentStatisticsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<StudentStatisticsRecord, ?>>asList(Keys.STUDENT_STATISTICS__FK_STUDENT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentStatistics as(String alias) {
		return new StudentStatistics(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StudentStatistics rename(String name) {
		return new StudentStatistics(name, null);
	}
}
