/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.StudentResultRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentResult extends org.jooq.impl.TableImpl<StudentResultRecord> {

	private static final long serialVersionUID = -824962306;

	/**
	 * The singleton instance of <code>public.student_result</code>
	 */
	public static final StudentResult STUDENT_RESULT = new StudentResult();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudentResultRecord> getRecordType() {
		return StudentResultRecord.class;
	}

	/**
	 * The column <code>public.student_result.id</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.student_result.text</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>public.student_result.ball</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, Integer> BALL = createField("ball", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_result.success_question</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, Integer> SUCCESS_QUESTION = createField("success_question", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_result.all_questions</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, Integer> ALL_QUESTIONS = createField("all_questions", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.student_result.time_start</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, java.sql.Timestamp> TIME_START = createField("time_start", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.student_result.time_end</code>.
	 */
	public final org.jooq.TableField<StudentResultRecord, java.sql.Timestamp> TIME_END = createField("time_end", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>public.student_result</code> table reference
	 */
	public StudentResult() {
		this("student_result", null);
	}

	/**
	 * Create an aliased <code>public.student_result</code> table reference
	 */
	public StudentResult(String alias) {
		this(alias, StudentResult.STUDENT_RESULT);
	}

	private StudentResult(String alias, org.jooq.Table<StudentResultRecord> aliased) {
		this(alias, aliased, null);
	}

	private StudentResult(String alias, org.jooq.Table<StudentResultRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<StudentResultRecord> getPrimaryKey() {
		return Keys.PK_STUDENT_RESULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<StudentResultRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<StudentResultRecord>>asList(Keys.PK_STUDENT_RESULT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentResult as(String alias) {
		return new StudentResult(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StudentResult rename(String name) {
		return new StudentResult(name, null);
	}
}
