/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.StudentRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends org.jooq.impl.TableImpl<StudentRecord> {

	private static final long serialVersionUID = 2130864978;

	/**
	 * The singleton instance of <code>public.student</code>
	 */
	public static final Student STUDENT = new Student();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudentRecord> getRecordType() {
		return StudentRecord.class;
	}

	/**
	 * The column <code>public.student.id</code>.
	 */
	public final org.jooq.TableField<StudentRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.student.name</code>.
	 */
	public final org.jooq.TableField<StudentRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>public.student.full_name</code>.
	 */
	public final org.jooq.TableField<StudentRecord, String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.student.username</code>.
	 */
	public final org.jooq.TableField<StudentRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.student.edu_group_id</code>.
	 */
	public final org.jooq.TableField<StudentRecord, Integer> EDU_GROUP_ID = createField("edu_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.student</code> table reference
	 */
	public Student() {
		this("student", null);
	}

	/**
	 * Create an aliased <code>public.student</code> table reference
	 */
	public Student(String alias) {
		this(alias, Student.STUDENT);
	}

	private Student(String alias, org.jooq.Table<StudentRecord> aliased) {
		this(alias, aliased, null);
	}

	private Student(String alias, org.jooq.Table<StudentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<StudentRecord> getPrimaryKey() {
		return Keys.PK_STUDENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<StudentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<StudentRecord>>asList(Keys.PK_STUDENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<StudentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<StudentRecord, ?>>asList(Keys.STUDENT__FK_STUDENT_PERSON, Keys.STUDENT__FK_STUDENT_EDU_GROUP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Student as(String alias) {
		return new Student(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Student rename(String name) {
		return new Student(name, null);
	}
}
