/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.StudiesCourseRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudiesCourse extends org.jooq.impl.TableImpl<StudiesCourseRecord> {

	private static final long serialVersionUID = 1264448400;

	/**
	 * The singleton instance of <code>public.studies_course</code>
	 */
	public static final StudiesCourse STUDIES_COURSE = new StudiesCourse();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudiesCourseRecord> getRecordType() {
		return StudiesCourseRecord.class;
	}

	/**
	 * The column <code>public.studies_course.id</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.studies_course.name</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.studies_course.description</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

	/**
	 * The column <code>public.studies_course.date_start</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, java.sql.Timestamp> DATE_START = createField("date_start", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.studies_course.date_end</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, java.sql.Timestamp> DATE_END = createField("date_end", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.studies_course.state</code>.
	 */
	public final org.jooq.TableField<StudiesCourseRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.studies_course</code> table reference
	 */
	public StudiesCourse() {
		this("studies_course", null);
	}

	/**
	 * Create an aliased <code>public.studies_course</code> table reference
	 */
	public StudiesCourse(String alias) {
		this(alias, StudiesCourse.STUDIES_COURSE);
	}

	private StudiesCourse(String alias, org.jooq.Table<StudiesCourseRecord> aliased) {
		this(alias, aliased, null);
	}

	private StudiesCourse(String alias, org.jooq.Table<StudiesCourseRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<StudiesCourseRecord> getPrimaryKey() {
		return Keys.PK_STUDIES_COURSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<StudiesCourseRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<StudiesCourseRecord>>asList(Keys.PK_STUDIES_COURSE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudiesCourse as(String alias) {
		return new StudiesCourse(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StudiesCourse rename(String name) {
		return new StudiesCourse(name, null);
	}
}
