/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables;

import ua.org.pius.studtrain.db.Keys;
import ua.org.pius.studtrain.db.Public;
import ua.org.pius.studtrain.db.tables.records.UserRolesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends org.jooq.impl.TableImpl<UserRolesRecord> {

	private static final long serialVersionUID = -291434160;

	/**
	 * The singleton instance of <code>public.user_roles</code>
	 */
	public static final UserRoles USER_ROLES = new UserRoles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserRolesRecord> getRecordType() {
		return UserRolesRecord.class;
	}

	/**
	 * The column <code>public.user_roles.username</code>.
	 */
	public final org.jooq.TableField<UserRolesRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.user_roles.rolename</code>.
	 */
	public final org.jooq.TableField<UserRolesRecord, String> ROLENAME = createField("rolename", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * Create a <code>public.user_roles</code> table reference
	 */
	public UserRoles() {
		this("user_roles", null);
	}

	/**
	 * Create an aliased <code>public.user_roles</code> table reference
	 */
	public UserRoles(String alias) {
		this(alias, UserRoles.USER_ROLES);
	}

	private UserRoles(String alias, org.jooq.Table<UserRolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserRoles(String alias, org.jooq.Table<UserRolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<UserRolesRecord> getPrimaryKey() {
		return Keys.PK_USER_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<UserRolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<UserRolesRecord>>asList(Keys.PK_USER_ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<UserRolesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<UserRolesRecord, ?>>asList(Keys.USER_ROLES__FK_USER_ROLES_USERS, Keys.USER_ROLES__FK_USER_ROLES_ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRoles as(String alias) {
		return new UserRoles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserRoles rename(String name) {
		return new UserRoles(name, null);
	}
}
