/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.EduGroup;
import ua.org.pius.studtrain.db.tables.records.EduGroupRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroupDao extends org.jooq.impl.DAOImpl<EduGroupRecord, EduGroup, Integer> {

	/**
	 * Create a new EduGroupDao without any configuration
	 */
	public EduGroupDao() {
		super(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP, EduGroup.class);
	}

	/**
	 * Create a new EduGroupDao with an attached configuration
	 */
	public EduGroupDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP, EduGroup.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(EduGroup object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<EduGroup> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public EduGroup fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<EduGroup> fetchByName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP.NAME, values);
	}

	/**
	 * Fetch records that have <code>instructor IN (values)</code>
	 */
	public java.util.List<EduGroup> fetchByInstructor(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroup.EDU_GROUP.INSTRUCTOR, values);
	}
}
