/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.EduGroupCourse;
import ua.org.pius.studtrain.db.tables.records.EduGroupCourseRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroupCourseDao extends org.jooq.impl.DAOImpl<EduGroupCourseRecord, EduGroupCourse, Integer> {

	/**
	 * Create a new EduGroupCourseDao without any configuration
	 */
	public EduGroupCourseDao() {
		super(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE, EduGroupCourse.class);
	}

	/**
	 * Create a new EduGroupCourseDao with an attached configuration
	 */
	public EduGroupCourseDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE, EduGroupCourse.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(EduGroupCourse object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<EduGroupCourse> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public EduGroupCourse fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE.ID, value);
	}

	/**
	 * Fetch records that have <code>edu_group_id IN (values)</code>
	 */
	public java.util.List<EduGroupCourse> fetchByEduGroupId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE.EDU_GROUP_ID, values);
	}

	/**
	 * Fetch records that have <code>studies_course_id IN (values)</code>
	 */
	public java.util.List<EduGroupCourse> fetchByStudiesCourseId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.EduGroupCourse.EDU_GROUP_COURSE.STUDIES_COURSE_ID, values);
	}
}
