/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.ExamTreeNode;
import ua.org.pius.studtrain.db.tables.records.ExamTreeNodeRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamTreeNodeDao extends org.jooq.impl.DAOImpl<ExamTreeNodeRecord, ExamTreeNode, Integer> {

	/**
	 * Create a new ExamTreeNodeDao without any configuration
	 */
	public ExamTreeNodeDao() {
		super(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.class);
	}

	/**
	 * Create a new ExamTreeNodeDao with an attached configuration
	 */
	public ExamTreeNodeDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ExamTreeNode object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ExamTreeNode> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ExamTreeNode fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE.ID, value);
	}

	/**
	 * Fetch records that have <code>exam_id IN (values)</code>
	 */
	public java.util.List<ExamTreeNode> fetchByExamId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE.EXAM_ID, values);
	}

	/**
	 * Fetch records that have <code>theme_id IN (values)</code>
	 */
	public java.util.List<ExamTreeNode> fetchByThemeId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE.THEME_ID, values);
	}

	/**
	 * Fetch records that have <code>exam_rule_id IN (values)</code>
	 */
	public java.util.List<ExamTreeNode> fetchByExamRuleId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.ExamTreeNode.EXAM_TREE_NODE.EXAM_RULE_ID, values);
	}
}
