/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.ExamRule;
import ua.org.pius.studtrain.db.tables.records.ExamRuleRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamRuleDao extends org.jooq.impl.DAOImpl<ExamRuleRecord, ua.org.pius.studtrain.db.tables.pojos.ExamRule, Integer> {

	/**
	 * Create a new ExamRuleDao without any configuration
	 */
	public ExamRuleDao() {
		super(ExamRule.EXAM_RULE, ua.org.pius.studtrain.db.tables.pojos.ExamRule.class);
	}

	/**
	 * Create a new ExamRuleDao with an attached configuration
	 */
	public ExamRuleDao(org.jooq.Configuration configuration) {
		super(ExamRule.EXAM_RULE, ua.org.pius.studtrain.db.tables.pojos.ExamRule.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ua.org.pius.studtrain.db.tables.pojos.ExamRule object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.ExamRule> fetchById(Integer... values) {
		return fetch(ExamRule.EXAM_RULE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.ExamRule fetchOneById(Integer value) {
		return fetchOne(ExamRule.EXAM_RULE.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.ExamRule> fetchByName(String... values) {
		return fetch(ExamRule.EXAM_RULE.NAME, values);
	}

	/**
	 * Fetch records that have <code>num_questions IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.ExamRule> fetchByNumQuestions(Integer... values) {
		return fetch(ExamRule.EXAM_RULE.NUM_QUESTIONS, values);
	}
}
