/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.Exam;
import ua.org.pius.studtrain.db.tables.records.ExamRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamDao extends org.jooq.impl.DAOImpl<ExamRecord, Exam, Integer> {

	/**
	 * Create a new ExamDao without any configuration
	 */
	public ExamDao() {
		super(ua.org.pius.studtrain.db.tables.Exam.EXAM, Exam.class);
	}

	/**
	 * Create a new ExamDao with an attached configuration
	 */
	public ExamDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.Exam.EXAM, Exam.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Exam object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<Exam> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Exam fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.Exam.EXAM.ID, value);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<Exam> fetchByType(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.TYPE, values);
	}

	/**
	 * Fetch records that have <code>time_start IN (values)</code>
	 */
	public java.util.List<Exam> fetchByTimeStart(java.sql.Timestamp... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.TIME_START, values);
	}

	/**
	 * Fetch records that have <code>time_end IN (values)</code>
	 */
	public java.util.List<Exam> fetchByTimeEnd(java.sql.Timestamp... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.TIME_END, values);
	}

	/**
	 * Fetch records that have <code>time_limit IN (values)</code>
	 */
	public java.util.List<Exam> fetchByTimeLimit(java.sql.Timestamp... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.TIME_LIMIT, values);
	}

	/**
	 * Fetch records that have <code>edu_group_course_id IN (values)</code>
	 */
	public java.util.List<Exam> fetchByEduGroupCourseId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.EDU_GROUP_COURSE_ID, values);
	}

	/**
	 * Fetch records that have <code>examenator_name IN (values)</code>
	 */
	public java.util.List<Exam> fetchByExamenatorName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.EXAMENATOR_NAME, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<Exam> fetchByName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.NAME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<Exam> fetchByDescription(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>ball IN (values)</code>
	 */
	public java.util.List<Exam> fetchByBall(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.BALL, values);
	}

	/**
	 * Fetch records that have <code>min_ball IN (values)</code>
	 */
	public java.util.List<Exam> fetchByMinBall(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Exam.EXAM.MIN_BALL, values);
	}
}
