/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.Privs;
import ua.org.pius.studtrain.db.tables.records.PrivsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivsDao extends org.jooq.impl.DAOImpl<PrivsRecord, ua.org.pius.studtrain.db.tables.pojos.Privs, String> {

	/**
	 * Create a new PrivsDao without any configuration
	 */
	public PrivsDao() {
		super(Privs.PRIVS, ua.org.pius.studtrain.db.tables.pojos.Privs.class);
	}

	/**
	 * Create a new PrivsDao with an attached configuration
	 */
	public PrivsDao(org.jooq.Configuration configuration) {
		super(Privs.PRIVS, ua.org.pius.studtrain.db.tables.pojos.Privs.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(ua.org.pius.studtrain.db.tables.pojos.Privs object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Privs> fetchById(String... values) {
		return fetch(Privs.PRIVS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.Privs fetchOneById(String value) {
		return fetchOne(Privs.PRIVS.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Privs> fetchByName(String... values) {
		return fetch(Privs.PRIVS.NAME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Privs> fetchByDescription(String... values) {
		return fetch(Privs.PRIVS.DESCRIPTION, values);
	}
}
