/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.Question;
import ua.org.pius.studtrain.db.tables.records.QuestionRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionDao extends org.jooq.impl.DAOImpl<QuestionRecord, Question, Integer> {

	/**
	 * Create a new QuestionDao without any configuration
	 */
	public QuestionDao() {
		super(ua.org.pius.studtrain.db.tables.Question.QUESTION, Question.class);
	}

	/**
	 * Create a new QuestionDao with an attached configuration
	 */
	public QuestionDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.Question.QUESTION, Question.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Question object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<Question> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Question.QUESTION.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Question fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.Question.QUESTION.ID, value);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public java.util.List<Question> fetchByText(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Question.QUESTION.TEXT, values);
	}

	/**
	 * Fetch records that have <code>ball IN (values)</code>
	 */
	public java.util.List<Question> fetchByBall(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Question.QUESTION.BALL, values);
	}

	/**
	 * Fetch records that have <code>question_type_id IN (values)</code>
	 */
	public java.util.List<Question> fetchByQuestionTypeId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Question.QUESTION.QUESTION_TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>theme_id IN (values)</code>
	 */
	public java.util.List<Question> fetchByThemeId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Question.QUESTION.THEME_ID, values);
	}
}
