/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.QuestionStatistics;
import ua.org.pius.studtrain.db.tables.records.QuestionStatisticsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionStatisticsDao extends org.jooq.impl.DAOImpl<QuestionStatisticsRecord, QuestionStatistics, Integer> {

	/**
	 * Create a new QuestionStatisticsDao without any configuration
	 */
	public QuestionStatisticsDao() {
		super(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS, QuestionStatistics.class);
	}

	/**
	 * Create a new QuestionStatisticsDao with an attached configuration
	 */
	public QuestionStatisticsDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS, QuestionStatistics.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(QuestionStatistics object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public QuestionStatistics fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.ID, value);
	}

	/**
	 * Fetch records that have <code>number_exam_for_theme IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberExamForTheme(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_EXAM_FOR_THEME, values);
	}

	/**
	 * Fetch records that have <code>number_exam_for_question IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberExamForQuestion(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_EXAM_FOR_QUESTION, values);
	}

	/**
	 * Fetch records that have <code>number_corrects IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberCorrects(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_CORRECTS, values);
	}

	/**
	 * Fetch records that have <code>number_incorrects IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberIncorrects(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_INCORRECTS, values);
	}

	/**
	 * Fetch records that have <code>number_rejections IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberRejections(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_REJECTIONS, values);
	}

	/**
	 * Fetch records that have <code>number_timeout IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByNumberTimeout(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.NUMBER_TIMEOUT, values);
	}

	/**
	 * Fetch records that have <code>summ_ball_possible IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchBySummBallPossible(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.SUMM_BALL_POSSIBLE, values);
	}

	/**
	 * Fetch records that have <code>summ_ball IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchBySummBall(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.SUMM_BALL, values);
	}

	/**
	 * Fetch records that have <code>question_id IN (values)</code>
	 */
	public java.util.List<QuestionStatistics> fetchByQuestionId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.QuestionStatistics.QUESTION_STATISTICS.QUESTION_ID, values);
	}
}
