/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.RolePrivs;
import ua.org.pius.studtrain.db.tables.records.RolePrivsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivsDao extends org.jooq.impl.DAOImpl<RolePrivsRecord, RolePrivs, org.jooq.Record2<String, String>> {

	/**
	 * Create a new RolePrivsDao without any configuration
	 */
	public RolePrivsDao() {
		super(ua.org.pius.studtrain.db.tables.RolePrivs.ROLE_PRIVS, RolePrivs.class);
	}

	/**
	 * Create a new RolePrivsDao with an attached configuration
	 */
	public RolePrivsDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.RolePrivs.ROLE_PRIVS, RolePrivs.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<String, String> getId(RolePrivs object) {
		return compositeKeyRecord(object.getRolename(), object.getPrivilegeId());
	}

	/**
	 * Fetch records that have <code>rolename IN (values)</code>
	 */
	public java.util.List<RolePrivs> fetchByRolename(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.RolePrivs.ROLE_PRIVS.ROLENAME, values);
	}

	/**
	 * Fetch records that have <code>privilege_id IN (values)</code>
	 */
	public java.util.List<RolePrivs> fetchByPrivilegeId(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.RolePrivs.ROLE_PRIVS.PRIVILEGE_ID, values);
	}
}
