/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.Roles;
import ua.org.pius.studtrain.db.tables.records.RolesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesDao extends org.jooq.impl.DAOImpl<RolesRecord, ua.org.pius.studtrain.db.tables.pojos.Roles, String> {

	/**
	 * Create a new RolesDao without any configuration
	 */
	public RolesDao() {
		super(Roles.ROLES, ua.org.pius.studtrain.db.tables.pojos.Roles.class);
	}

	/**
	 * Create a new RolesDao with an attached configuration
	 */
	public RolesDao(org.jooq.Configuration configuration) {
		super(Roles.ROLES, ua.org.pius.studtrain.db.tables.pojos.Roles.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(ua.org.pius.studtrain.db.tables.pojos.Roles object) {
		return object.getRolename();
	}

	/**
	 * Fetch records that have <code>rolename IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Roles> fetchByRolename(String... values) {
		return fetch(Roles.ROLES.ROLENAME, values);
	}

	/**
	 * Fetch a unique record that has <code>rolename = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.Roles fetchOneByRolename(String value) {
		return fetchOne(Roles.ROLES.ROLENAME, value);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Roles> fetchByCreatedAt(java.sql.Timestamp... values) {
		return fetch(Roles.ROLES.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>printname IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Roles> fetchByPrintname(String... values) {
		return fetch(Roles.ROLES.PRINTNAME, values);
	}
}
