/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.Shadow;
import ua.org.pius.studtrain.db.tables.records.ShadowRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShadowDao extends org.jooq.impl.DAOImpl<ShadowRecord, ua.org.pius.studtrain.db.tables.pojos.Shadow, String> {

	/**
	 * Create a new ShadowDao without any configuration
	 */
	public ShadowDao() {
		super(Shadow.SHADOW, ua.org.pius.studtrain.db.tables.pojos.Shadow.class);
	}

	/**
	 * Create a new ShadowDao with an attached configuration
	 */
	public ShadowDao(org.jooq.Configuration configuration) {
		super(Shadow.SHADOW, ua.org.pius.studtrain.db.tables.pojos.Shadow.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(ua.org.pius.studtrain.db.tables.pojos.Shadow object) {
		return object.getUsername();
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Shadow> fetchByUsername(String... values) {
		return fetch(Shadow.SHADOW.USERNAME, values);
	}

	/**
	 * Fetch a unique record that has <code>username = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.Shadow fetchOneByUsername(String value) {
		return fetchOne(Shadow.SHADOW.USERNAME, value);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.Shadow> fetchByPassword(String... values) {
		return fetch(Shadow.SHADOW.PASSWORD, values);
	}
}
