/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.StudentStatistics;
import ua.org.pius.studtrain.db.tables.records.StudentStatisticsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentStatisticsDao extends org.jooq.impl.DAOImpl<StudentStatisticsRecord, StudentStatistics, Integer> {

	/**
	 * Create a new StudentStatisticsDao without any configuration
	 */
	public StudentStatisticsDao() {
		super(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS, StudentStatistics.class);
	}

	/**
	 * Create a new StudentStatisticsDao with an attached configuration
	 */
	public StudentStatisticsDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS, StudentStatistics.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(StudentStatistics object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public StudentStatistics fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.ID, value);
	}

	/**
	 * Fetch records that have <code>number_exam_for_group IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberExamForGroup(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_EXAM_FOR_GROUP, values);
	}

	/**
	 * Fetch records that have <code>number_exam_for_stud IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberExamForStud(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_EXAM_FOR_STUD, values);
	}

	/**
	 * Fetch records that have <code>number_corrects IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberCorrects(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_CORRECTS, values);
	}

	/**
	 * Fetch records that have <code>number_incorrects IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberIncorrects(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_INCORRECTS, values);
	}

	/**
	 * Fetch records that have <code>number_rejections IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberRejections(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_REJECTIONS, values);
	}

	/**
	 * Fetch records that have <code>number_timeout IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByNumberTimeout(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.NUMBER_TIMEOUT, values);
	}

	/**
	 * Fetch records that have <code>summ_ball_possible IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchBySummBallPossible(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.SUMM_BALL_POSSIBLE, values);
	}

	/**
	 * Fetch records that have <code>summ_ball IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchBySummBall(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.SUMM_BALL, values);
	}

	/**
	 * Fetch records that have <code>student_id IN (values)</code>
	 */
	public java.util.List<StudentStatistics> fetchByStudentId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.StudentStatistics.STUDENT_STATISTICS.STUDENT_ID, values);
	}
}
