/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.StudentResult;
import ua.org.pius.studtrain.db.tables.records.StudentResultRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentResultDao extends org.jooq.impl.DAOImpl<StudentResultRecord, ua.org.pius.studtrain.db.tables.pojos.StudentResult, Integer> {

	/**
	 * Create a new StudentResultDao without any configuration
	 */
	public StudentResultDao() {
		super(StudentResult.STUDENT_RESULT, ua.org.pius.studtrain.db.tables.pojos.StudentResult.class);
	}

	/**
	 * Create a new StudentResultDao with an attached configuration
	 */
	public StudentResultDao(org.jooq.Configuration configuration) {
		super(StudentResult.STUDENT_RESULT, ua.org.pius.studtrain.db.tables.pojos.StudentResult.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ua.org.pius.studtrain.db.tables.pojos.StudentResult object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchById(Integer... values) {
		return fetch(StudentResult.STUDENT_RESULT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.StudentResult fetchOneById(Integer value) {
		return fetchOne(StudentResult.STUDENT_RESULT.ID, value);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchByText(String... values) {
		return fetch(StudentResult.STUDENT_RESULT.TEXT, values);
	}

	/**
	 * Fetch records that have <code>ball IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchByBall(Integer... values) {
		return fetch(StudentResult.STUDENT_RESULT.BALL, values);
	}

	/**
	 * Fetch records that have <code>success_question IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchBySuccessQuestion(Integer... values) {
		return fetch(StudentResult.STUDENT_RESULT.SUCCESS_QUESTION, values);
	}

	/**
	 * Fetch records that have <code>all_questions IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchByAllQuestions(Integer... values) {
		return fetch(StudentResult.STUDENT_RESULT.ALL_QUESTIONS, values);
	}

	/**
	 * Fetch records that have <code>time_start IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchByTimeStart(java.sql.Timestamp... values) {
		return fetch(StudentResult.STUDENT_RESULT.TIME_START, values);
	}

	/**
	 * Fetch records that have <code>time_end IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentResult> fetchByTimeEnd(java.sql.Timestamp... values) {
		return fetch(StudentResult.STUDENT_RESULT.TIME_END, values);
	}
}
