/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.StudentTask;
import ua.org.pius.studtrain.db.tables.records.StudentTaskRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentTaskDao extends org.jooq.impl.DAOImpl<StudentTaskRecord, ua.org.pius.studtrain.db.tables.pojos.StudentTask, Integer> {

	/**
	 * Create a new StudentTaskDao without any configuration
	 */
	public StudentTaskDao() {
		super(StudentTask.STUDENT_TASK, ua.org.pius.studtrain.db.tables.pojos.StudentTask.class);
	}

	/**
	 * Create a new StudentTaskDao with an attached configuration
	 */
	public StudentTaskDao(org.jooq.Configuration configuration) {
		super(StudentTask.STUDENT_TASK, ua.org.pius.studtrain.db.tables.pojos.StudentTask.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ua.org.pius.studtrain.db.tables.pojos.StudentTask object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentTask> fetchById(Integer... values) {
		return fetch(StudentTask.STUDENT_TASK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.StudentTask fetchOneById(Integer value) {
		return fetchOne(StudentTask.STUDENT_TASK.ID, value);
	}

	/**
	 * Fetch records that have <code>student_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentTask> fetchByStudentId(Integer... values) {
		return fetch(StudentTask.STUDENT_TASK.STUDENT_ID, values);
	}

	/**
	 * Fetch records that have <code>exam_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentTask> fetchByExamId(Integer... values) {
		return fetch(StudentTask.STUDENT_TASK.EXAM_ID, values);
	}

	/**
	 * Fetch records that have <code>examination_ticket_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentTask> fetchByExaminationTicketId(Integer... values) {
		return fetch(StudentTask.STUDENT_TASK.EXAMINATION_TICKET_ID, values);
	}

	/**
	 * Fetch records that have <code>student_result_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.StudentTask> fetchByStudentResultId(Integer... values) {
		return fetch(StudentTask.STUDENT_TASK.STUDENT_RESULT_ID, values);
	}
}
