/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.Student;
import ua.org.pius.studtrain.db.tables.records.StudentRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentDao extends org.jooq.impl.DAOImpl<StudentRecord, Student, Integer> {

	/**
	 * Create a new StudentDao without any configuration
	 */
	public StudentDao() {
		super(ua.org.pius.studtrain.db.tables.Student.STUDENT, Student.class);
	}

	/**
	 * Create a new StudentDao with an attached configuration
	 */
	public StudentDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.Student.STUDENT, Student.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Student object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<Student> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Student.STUDENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Student fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.Student.STUDENT.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<Student> fetchByName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Student.STUDENT.NAME, values);
	}

	/**
	 * Fetch records that have <code>full_name IN (values)</code>
	 */
	public java.util.List<Student> fetchByFullName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Student.STUDENT.FULL_NAME, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<Student> fetchByUsername(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Student.STUDENT.USERNAME, values);
	}

	/**
	 * Fetch records that have <code>edu_group_id IN (values)</code>
	 */
	public java.util.List<Student> fetchByEduGroupId(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Student.STUDENT.EDU_GROUP_ID, values);
	}
}
