/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.TaskQuestions;
import ua.org.pius.studtrain.db.tables.records.TaskQuestionsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskQuestionsDao extends org.jooq.impl.DAOImpl<TaskQuestionsRecord, ua.org.pius.studtrain.db.tables.pojos.TaskQuestions, Integer> {

	/**
	 * Create a new TaskQuestionsDao without any configuration
	 */
	public TaskQuestionsDao() {
		super(TaskQuestions.TASK_QUESTIONS, ua.org.pius.studtrain.db.tables.pojos.TaskQuestions.class);
	}

	/**
	 * Create a new TaskQuestionsDao with an attached configuration
	 */
	public TaskQuestionsDao(org.jooq.Configuration configuration) {
		super(TaskQuestions.TASK_QUESTIONS, ua.org.pius.studtrain.db.tables.pojos.TaskQuestions.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ua.org.pius.studtrain.db.tables.pojos.TaskQuestions object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.TaskQuestions> fetchById(Integer... values) {
		return fetch(TaskQuestions.TASK_QUESTIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ua.org.pius.studtrain.db.tables.pojos.TaskQuestions fetchOneById(Integer value) {
		return fetchOne(TaskQuestions.TASK_QUESTIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>student_task_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.TaskQuestions> fetchByStudentTaskId(Integer... values) {
		return fetch(TaskQuestions.TASK_QUESTIONS.STUDENT_TASK_ID, values);
	}

	/**
	 * Fetch records that have <code>question_id IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.TaskQuestions> fetchByQuestionId(Integer... values) {
		return fetch(TaskQuestions.TASK_QUESTIONS.QUESTION_ID, values);
	}
}
