/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.Theme;
import ua.org.pius.studtrain.db.tables.records.ThemeRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThemeDao extends org.jooq.impl.DAOImpl<ThemeRecord, Theme, Integer> {

	/**
	 * Create a new ThemeDao without any configuration
	 */
	public ThemeDao() {
		super(ua.org.pius.studtrain.db.tables.Theme.THEME, Theme.class);
	}

	/**
	 * Create a new ThemeDao with an attached configuration
	 */
	public ThemeDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.Theme.THEME, Theme.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Theme object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<Theme> fetchById(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Theme fetchOneById(Integer value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.Theme.THEME.ID, value);
	}

	/**
	 * Fetch records that have <code>parent IN (values)</code>
	 */
	public java.util.List<Theme> fetchByParent(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.PARENT, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<Theme> fetchByName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.NAME, values);
	}

	/**
	 * Fetch records that have <code>creator_name IN (values)</code>
	 */
	public java.util.List<Theme> fetchByCreatorName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.CREATOR_NAME, values);
	}

	/**
	 * Fetch records that have <code>rgt IN (values)</code>
	 */
	public java.util.List<Theme> fetchByRgt(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.RGT, values);
	}

	/**
	 * Fetch records that have <code>lft IN (values)</code>
	 */
	public java.util.List<Theme> fetchByLft(Integer... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Theme.THEME.LFT, values);
	}
}
