/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.pojos.Users;
import ua.org.pius.studtrain.db.tables.records.UsersRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends org.jooq.impl.DAOImpl<UsersRecord, Users, String> {

	/**
	 * Create a new UsersDao without any configuration
	 */
	public UsersDao() {
		super(ua.org.pius.studtrain.db.tables.Users.USERS, Users.class);
	}

	/**
	 * Create a new UsersDao with an attached configuration
	 */
	public UsersDao(org.jooq.Configuration configuration) {
		super(ua.org.pius.studtrain.db.tables.Users.USERS, Users.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(Users object) {
		return object.getUsername();
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<Users> fetchByUsername(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.USERNAME, values);
	}

	/**
	 * Fetch a unique record that has <code>username = value</code>
	 */
	public Users fetchOneByUsername(String value) {
		return fetchOne(ua.org.pius.studtrain.db.tables.Users.USERS.USERNAME, value);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public java.util.List<Users> fetchByCreatedAt(java.sql.Timestamp... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>activation IN (values)</code>
	 */
	public java.util.List<Users> fetchByActivation(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.ACTIVATION, values);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public java.util.List<Users> fetchByFirstName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public java.util.List<Users> fetchByLastName(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>gender IN (values)</code>
	 */
	public java.util.List<Users> fetchByGender(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.GENDER, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<Users> fetchByEmail(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public java.util.List<Users> fetchByPhone(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.PHONE, values);
	}

	/**
	 * Fetch records that have <code>activation_key IN (values)</code>
	 */
	public java.util.List<Users> fetchByActivationKey(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.ACTIVATION_KEY, values);
	}

	/**
	 * Fetch records that have <code>params IN (values)</code>
	 */
	public java.util.List<Users> fetchByParams(String... values) {
		return fetch(ua.org.pius.studtrain.db.tables.Users.USERS.PARAMS, values);
	}
}
