/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.daos;

import ua.org.pius.studtrain.db.tables.UserRoles;
import ua.org.pius.studtrain.db.tables.records.UserRolesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolesDao extends org.jooq.impl.DAOImpl<UserRolesRecord, ua.org.pius.studtrain.db.tables.pojos.UserRoles, org.jooq.Record2<String, String>> {

	/**
	 * Create a new UserRolesDao without any configuration
	 */
	public UserRolesDao() {
		super(UserRoles.USER_ROLES, ua.org.pius.studtrain.db.tables.pojos.UserRoles.class);
	}

	/**
	 * Create a new UserRolesDao with an attached configuration
	 */
	public UserRolesDao(org.jooq.Configuration configuration) {
		super(UserRoles.USER_ROLES, ua.org.pius.studtrain.db.tables.pojos.UserRoles.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<String, String> getId(ua.org.pius.studtrain.db.tables.pojos.UserRoles object) {
		return compositeKeyRecord(object.getUsername(), object.getRolename());
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.UserRoles> fetchByUsername(String... values) {
		return fetch(UserRoles.USER_ROLES.USERNAME, values);
	}

	/**
	 * Fetch records that have <code>rolename IN (values)</code>
	 */
	public java.util.List<ua.org.pius.studtrain.db.tables.pojos.UserRoles> fetchByRolename(String... values) {
		return fetch(UserRoles.USER_ROLES.ROLENAME, values);
	}
}
