DROP SEQUENCE seq_pk_answer;
DROP SEQUENCE seq_pk_edu_group;
DROP SEQUENCE seq_pk_edu_group_course;
DROP SEQUENCE seq_pk_exam;
DROP SEQUENCE seq_pk_exam_rule;
DROP SEQUENCE seq_pk_exam_tree_node;
DROP SEQUENCE seq_pk_question;
DROP SEQUENCE seq_pk_question_statistics;
DROP SEQUENCE seq_pk_question_type;
DROP SEQUENCE seq_pk_student;
DROP SEQUENCE seq_pk_student_result;
DROP SEQUENCE seq_pk_student_statistics;
DROP SEQUENCE seq_pk_student_task;
DROP SEQUENCE seq_pk_studies_course;
DROP SEQUENCE seq_pk_task_answer;
DROP SEQUENCE seq_pk_task_questions;
DROP SEQUENCE seq_pk_theme;
DROP SEQUENCE SEQ_PK_EXAMINATION_TICKET;


ALTER TABLE user_roles DROP CONSTRAINT fk_user_roles_users;
ALTER TABLE user_roles DROP CONSTRAINT fk_user_roles_roles;
ALTER TABLE task_answer DROP CONSTRAINT fk_task_answer_answer;
ALTER TABLE task_answer DROP CONSTRAINT fk_task_answer_task_questions;
ALTER TABLE student_statistics DROP CONSTRAINT fk_student_id;
ALTER TABLE shadow DROP CONSTRAINT fk_shadow_users;
ALTER TABLE question_statistics DROP CONSTRAINT fk_question_id;
ALTER TABLE logs DROP CONSTRAINT fk_logs_users;
ALTER TABLE exam_tree_node DROP CONSTRAINT fk_exam_tree_node_exam_rule;
ALTER TABLE exam_tree_node DROP CONSTRAINT fk_exam_tree_node_exam;
ALTER TABLE exam_tree_node DROP CONSTRAINT fk_exam_tree_node_theme;
ALTER TABLE student_task DROP CONSTRAINT fk_student_task_student_result;
ALTER TABLE student_task DROP CONSTRAINT fk_student_task_exam;
ALTER TABLE student_task DROP CONSTRAINT fk_student_task_student;
ALTER TABLE theme DROP CONSTRAINT fk_theme_user;
ALTER TABLE theme DROP CONSTRAINT fk_theme_theme;
ALTER TABLE task_questions DROP CONSTRAINT fk_task_questions_question;
ALTER TABLE task_questions DROP CONSTRAINT fk_task_questions_student_task;
ALTER TABLE student DROP CONSTRAINT fk_student_edu_group;
ALTER TABLE student DROP CONSTRAINT fk_student_person;
ALTER TABLE question DROP CONSTRAINT fk_question_theme;
ALTER TABLE question DROP CONSTRAINT fk_question_question_type;
ALTER TABLE exam DROP CONSTRAINT fk_exam_users;
ALTER TABLE exam DROP CONSTRAINT fk_exam_edu_group_course;
ALTER TABLE edu_group_course DROP CONSTRAINT fk_edu_group_course_edu_group;
ALTER TABLE edu_group_course DROP CONSTRAINT fk_edu_group_course_studies_course;
ALTER TABLE edu_group DROP CONSTRAINT fk_edu_group_users;
ALTER TABLE answer DROP CONSTRAINT fk_answer_question;
ALTER TABLE role_privs DROP CONSTRAINT FK_role_privs_privs;
ALTER TABLE role_privs DROP CONSTRAINT FK_role_privs_roles;
ALTER TABLE examination_ticket DROP CONSTRAINT fk_examination_ticket_exam;
ALTER TABLE student_task DROP CONSTRAINT fk_student_task_examination_ticket;

ALTER TABLE privs DROP CONSTRAINT PK_PRIVS;
ALTER TABLE role_privs DROP CONSTRAINT PK_ROLE_PRIVS;
ALTER TABLE roles DROP CONSTRAINT PK_ROLES;
ALTER TABLE user_roles DROP CONSTRAINT PK_USER_ROLES;
ALTER TABLE users DROP CONSTRAINT PK_USERS;
ALTER TABLE edu_group DROP CONSTRAINT PK_EDU_GROUP;
ALTER TABLE student DROP CONSTRAINT PK_STUDENT;
ALTER TABLE student_statistics DROP CONSTRAINT PK_STUDENT_STATISTICS;
ALTER TABLE theme DROP CONSTRAINT PK_THEME;
ALTER TABLE question_type DROP CONSTRAINT PK_QUESTION_TYPE;
ALTER TABLE question DROP CONSTRAINT PK_QUESTION;
ALTER TABLE question_statistics DROP CONSTRAINT PK_QUESTION_STATISTICS;
ALTER TABLE shadow DROP CONSTRAINT PK_SHADOW;
ALTER TABLE logs DROP CONSTRAINT PK_LOGS;
ALTER TABLE studies_course DROP CONSTRAINT PK_STUDIES_COURSE;
ALTER TABLE EDU_GROUP_COURSE DROP CONSTRAINT PK_EDU_GROUP_COURSE;
ALTER TABLE exam DROP CONSTRAINT PK_EXAM;
ALTER TABLE student_result DROP CONSTRAINT PK_STUDENT_RESULT;
ALTER TABLE answer DROP CONSTRAINT PK_ANSWER;
ALTER TABLE student_task DROP CONSTRAINT PK_STUDENT_TASK;
ALTER TABLE exam_rule DROP CONSTRAINT PK_EXAM_RULE;
ALTER TABLE exam_tree_node DROP CONSTRAINT PK_EXAM_TREE_NODE;
ALTER TABLE task_questions DROP CONSTRAINT PK_TASK_QUESTIONS;
ALTER TABLE task_answer DROP CONSTRAINT PK_TASK_ANSWER;
ALTER TABLE examination_ticket DROP CONSTRAINT PK_EXAMINATION_TICKET;

DROP TABLE user_roles;
DROP TABLE task_answer;
DROP TABLE student_statistics;
DROP TABLE shadow;
DROP TABLE question_statistics;
DROP TABLE logs;
DROP TABLE exam_tree_node;
DROP TABLE student_task;
DROP TABLE theme;
DROP TABLE task_questions;
DROP TABLE student;
DROP TABLE question;
DROP TABLE exam;
DROP TABLE edu_group_course;
DROP TABLE edu_group;
DROP TABLE answer;
DROP TABLE users;
DROP TABLE studies_course;
DROP TABLE student_result;
DROP TABLE role_privs;
DROP TABLE roles;
DROP TABLE privs;
DROP TABLE question_type;
DROP TABLE exam_rule;
DROP TABLE examination_ticket;