/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroupCourse implements java.io.Serializable {

	private static final long serialVersionUID = 885585026;

	private Integer id;
	private Integer eduGroupId;
	private Integer studiesCourseId;

	public EduGroupCourse() {}

	public EduGroupCourse(
		Integer id,
		Integer eduGroupId,
		Integer studiesCourseId
	) {
		this.id = id;
		this.eduGroupId = eduGroupId;
		this.studiesCourseId = studiesCourseId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEduGroupId() {
		return this.eduGroupId;
	}

	public void setEduGroupId(Integer eduGroupId) {
		this.eduGroupId = eduGroupId;
	}

	public Integer getStudiesCourseId() {
		return this.studiesCourseId;
	}

	public void setStudiesCourseId(Integer studiesCourseId) {
		this.studiesCourseId = studiesCourseId;
	}
}
