/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1880392197;

	private Integer id;
	private String  name;
	private String  instructor;

	public EduGroup() {}

	public EduGroup(
		Integer id,
		String  name,
		String  instructor
	) {
		this.id = id;
		this.name = name;
		this.instructor = instructor;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInstructor() {
		return this.instructor;
	}

	public void setInstructor(String instructor) {
		this.instructor = instructor;
	}
}
