/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exam implements java.io.Serializable {

	private static final long serialVersionUID = 114024107;

	private Integer  id;
	private Integer  type;
	private java.sql.Timestamp timeStart;
	private java.sql.Timestamp timeEnd;
	private java.sql.Timestamp timeLimit;
	private Integer  eduGroupCourseId;
	private String   examenatorName;
	private String   name;
	private String   description;
	private Integer  ball;
	private Integer  minBall;

	public Exam() {}

	public Exam(
		Integer  id,
		Integer  type,
		java.sql.Timestamp timeStart,
		java.sql.Timestamp timeEnd,
		java.sql.Timestamp timeLimit,
		Integer  eduGroupCourseId,
		String   examenatorName,
		String   name,
		String   description,
		Integer  ball,
		Integer  minBall
	) {
		this.id = id;
		this.type = type;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeLimit = timeLimit;
		this.eduGroupCourseId = eduGroupCourseId;
		this.examenatorName = examenatorName;
		this.name = name;
		this.description = description;
		this.ball = ball;
		this.minBall = minBall;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public java.sql.Timestamp getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(java.sql.Timestamp timeStart) {
		this.timeStart = timeStart;
	}

	public java.sql.Timestamp getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(java.sql.Timestamp timeEnd) {
		this.timeEnd = timeEnd;
	}

	public java.sql.Timestamp getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(java.sql.Timestamp timeLimit) {
		this.timeLimit = timeLimit;
	}

	public Integer getEduGroupCourseId() {
		return this.eduGroupCourseId;
	}

	public void setEduGroupCourseId(Integer eduGroupCourseId) {
		this.eduGroupCourseId = eduGroupCourseId;
	}

	public String getExamenatorName() {
		return this.examenatorName;
	}

	public void setExamenatorName(String examenatorName) {
		this.examenatorName = examenatorName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getBall() {
		return this.ball;
	}

	public void setBall(Integer ball) {
		this.ball = ball;
	}

	public Integer getMinBall() {
		return this.minBall;
	}

	public void setMinBall(Integer minBall) {
		this.minBall = minBall;
	}
}
