/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamRule implements java.io.Serializable {

	private static final long serialVersionUID = 422607275;

	private Integer id;
	private String  name;
	private Integer numQuestions;

	public ExamRule() {}

	public ExamRule(
		Integer id,
		String  name,
		Integer numQuestions
	) {
		this.id = id;
		this.name = name;
		this.numQuestions = numQuestions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNumQuestions() {
		return this.numQuestions;
	}

	public void setNumQuestions(Integer numQuestions) {
		this.numQuestions = numQuestions;
	}
}
