/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamTreeNode implements java.io.Serializable {

	private static final long serialVersionUID = -612456145;

	private Integer id;
	private Integer examId;
	private Integer themeId;
	private Integer examRuleId;

	public ExamTreeNode() {}

	public ExamTreeNode(
		Integer id,
		Integer examId,
		Integer themeId,
		Integer examRuleId
	) {
		this.id = id;
		this.examId = examId;
		this.themeId = themeId;
		this.examRuleId = examRuleId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getExamId() {
		return this.examId;
	}

	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	public Integer getThemeId() {
		return this.themeId;
	}

	public void setThemeId(Integer themeId) {
		this.themeId = themeId;
	}

	public Integer getExamRuleId() {
		return this.examRuleId;
	}

	public void setExamRuleId(Integer examRuleId) {
		this.examRuleId = examRuleId;
	}
}
