/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionStatistics implements java.io.Serializable {

	private static final long serialVersionUID = -1878694987;

	private Integer id;
	private Integer numberExamForTheme;
	private Integer numberExamForQuestion;
	private Integer numberCorrects;
	private Integer numberIncorrects;
	private Integer numberRejections;
	private Integer numberTimeout;
	private Integer summBallPossible;
	private Integer summBall;
	private Integer questionId;

	public QuestionStatistics() {}

	public QuestionStatistics(
		Integer id,
		Integer numberExamForTheme,
		Integer numberExamForQuestion,
		Integer numberCorrects,
		Integer numberIncorrects,
		Integer numberRejections,
		Integer numberTimeout,
		Integer summBallPossible,
		Integer summBall,
		Integer questionId
	) {
		this.id = id;
		this.numberExamForTheme = numberExamForTheme;
		this.numberExamForQuestion = numberExamForQuestion;
		this.numberCorrects = numberCorrects;
		this.numberIncorrects = numberIncorrects;
		this.numberRejections = numberRejections;
		this.numberTimeout = numberTimeout;
		this.summBallPossible = summBallPossible;
		this.summBall = summBall;
		this.questionId = questionId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNumberExamForTheme() {
		return this.numberExamForTheme;
	}

	public void setNumberExamForTheme(Integer numberExamForTheme) {
		this.numberExamForTheme = numberExamForTheme;
	}

	public Integer getNumberExamForQuestion() {
		return this.numberExamForQuestion;
	}

	public void setNumberExamForQuestion(Integer numberExamForQuestion) {
		this.numberExamForQuestion = numberExamForQuestion;
	}

	public Integer getNumberCorrects() {
		return this.numberCorrects;
	}

	public void setNumberCorrects(Integer numberCorrects) {
		this.numberCorrects = numberCorrects;
	}

	public Integer getNumberIncorrects() {
		return this.numberIncorrects;
	}

	public void setNumberIncorrects(Integer numberIncorrects) {
		this.numberIncorrects = numberIncorrects;
	}

	public Integer getNumberRejections() {
		return this.numberRejections;
	}

	public void setNumberRejections(Integer numberRejections) {
		this.numberRejections = numberRejections;
	}

	public Integer getNumberTimeout() {
		return this.numberTimeout;
	}

	public void setNumberTimeout(Integer numberTimeout) {
		this.numberTimeout = numberTimeout;
	}

	public Integer getSummBallPossible() {
		return this.summBallPossible;
	}

	public void setSummBallPossible(Integer summBallPossible) {
		this.summBallPossible = summBallPossible;
	}

	public Integer getSummBall() {
		return this.summBall;
	}

	public void setSummBall(Integer summBall) {
		this.summBall = summBall;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}
}
