/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = -1490217149;

	private String   rolename;
	private java.sql.Timestamp createdAt;
	private String   printname;

	public Roles() {}

	public Roles(
		String   rolename,
		java.sql.Timestamp createdAt,
		String   printname
	) {
		this.rolename = rolename;
		this.createdAt = createdAt;
		this.printname = printname;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public String getPrintname() {
		return this.printname;
	}

	public void setPrintname(String printname) {
		this.printname = printname;
	}
}
