/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentTask implements java.io.Serializable {

	private static final long serialVersionUID = 1302817210;

	private Integer id;
	private Integer studentId;
	private Integer examId;
	private Integer examinationTicketId;
	private Integer studentResultId;

	public StudentTask() {}

	public StudentTask(
		Integer id,
		Integer studentId,
		Integer examId,
		Integer examinationTicketId,
		Integer studentResultId
	) {
		this.id = id;
		this.studentId = studentId;
		this.examId = examId;
		this.examinationTicketId = examinationTicketId;
		this.studentResultId = studentResultId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Integer getExamId() {
		return this.examId;
	}

	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	public Integer getExaminationTicketId() {
		return this.examinationTicketId;
	}

	public void setExaminationTicketId(Integer examinationTicketId) {
		this.examinationTicketId = examinationTicketId;
	}

	public Integer getStudentResultId() {
		return this.studentResultId;
	}

	public void setStudentResultId(Integer studentResultId) {
		this.studentResultId = studentResultId;
	}
}
