/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudiesCourse implements java.io.Serializable {

	private static final long serialVersionUID = -1687476920;

	private Integer  id;
	private String   name;
	private String   description;
	private java.sql.Timestamp dateStart;
	private java.sql.Timestamp dateEnd;
	private Integer  state;

	public StudiesCourse() {}

	public StudiesCourse(
		Integer  id,
		String   name,
		String   description,
		java.sql.Timestamp dateStart,
		java.sql.Timestamp dateEnd,
		Integer  state
	) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public java.sql.Timestamp getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(java.sql.Timestamp dateStart) {
		this.dateStart = dateStart;
	}

	public java.sql.Timestamp getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(java.sql.Timestamp dateEnd) {
		this.dateEnd = dateEnd;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}
}
