/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements java.io.Serializable {

	private static final long serialVersionUID = 405860481;

	private Integer id;
	private String  name;
	private String  fullName;
	private String  username;
	private Integer eduGroupId;

	public Student() {}

	public Student(
		Integer id,
		String  name,
		String  fullName,
		String  username,
		Integer eduGroupId
	) {
		this.id = id;
		this.name = name;
		this.fullName = fullName;
		this.username = username;
		this.eduGroupId = eduGroupId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getEduGroupId() {
		return this.eduGroupId;
	}

	public void setEduGroupId(Integer eduGroupId) {
		this.eduGroupId = eduGroupId;
	}
}
