/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskAnswer implements java.io.Serializable {

	private static final long serialVersionUID = 1368400233;

	private Integer id;
	private Integer taskQuestionsId;
	private Integer answerId;
	private String  text;

	public TaskAnswer() {}

	public TaskAnswer(
		Integer id,
		Integer taskQuestionsId,
		Integer answerId,
		String  text
	) {
		this.id = id;
		this.taskQuestionsId = taskQuestionsId;
		this.answerId = answerId;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskQuestionsId() {
		return this.taskQuestionsId;
	}

	public void setTaskQuestionsId(Integer taskQuestionsId) {
		this.taskQuestionsId = taskQuestionsId;
	}

	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}
}
