/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskQuestions implements java.io.Serializable {

	private static final long serialVersionUID = 1947706446;

	private Integer id;
	private Integer studentTaskId;
	private Integer questionId;

	public TaskQuestions() {}

	public TaskQuestions(
		Integer id,
		Integer studentTaskId,
		Integer questionId
	) {
		this.id = id;
		this.studentTaskId = studentTaskId;
		this.questionId = questionId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStudentTaskId() {
		return this.studentTaskId;
	}

	public void setStudentTaskId(Integer studentTaskId) {
		this.studentTaskId = studentTaskId;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}
}
