/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Theme implements java.io.Serializable {

	private static final long serialVersionUID = 210604355;

	private Integer id;
	private Integer parent;
	private String  name;
	private String  creatorName;
	private Integer rgt;
	private Integer lft;

	public Theme() {}

	public Theme(
		Integer id,
		Integer parent,
		String  name,
		String  creatorName,
		Integer rgt,
		Integer lft
	) {
		this.id = id;
		this.parent = parent;
		this.name = name;
		this.creatorName = creatorName;
		this.rgt = rgt;
		this.lft = lft;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatorName() {
		return this.creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}
}
