/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db;

import ua.org.pius.studtrain.db.tables.*;
import ua.org.pius.studtrain.db.tables.records.*;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<AnswerRecord> PK_ANSWER = UniqueKeys0.PK_ANSWER;
	public static final org.jooq.UniqueKey<EduGroupRecord> PK_EDU_GROUP = UniqueKeys0.PK_EDU_GROUP;
	public static final org.jooq.UniqueKey<EduGroupCourseRecord> PK_EDU_GROUP_COURSE = UniqueKeys0.PK_EDU_GROUP_COURSE;
	public static final org.jooq.UniqueKey<ExamRecord> PK_EXAM = UniqueKeys0.PK_EXAM;
	public static final org.jooq.UniqueKey<ExamRuleRecord> PK_EXAM_RULE = UniqueKeys0.PK_EXAM_RULE;
	public static final org.jooq.UniqueKey<ExamTreeNodeRecord> PK_EXAM_TREE_NODE = UniqueKeys0.PK_EXAM_TREE_NODE;
	public static final org.jooq.UniqueKey<ExaminationTicketRecord> PK_EXAMINATION_TICKET = UniqueKeys0.PK_EXAMINATION_TICKET;
	public static final org.jooq.UniqueKey<LogsRecord> PK_LOGS = UniqueKeys0.PK_LOGS;
	public static final org.jooq.UniqueKey<PrivsRecord> PK_PRIVS = UniqueKeys0.PK_PRIVS;
	public static final org.jooq.UniqueKey<QuestionRecord> PK_QUESTION = UniqueKeys0.PK_QUESTION;
	public static final org.jooq.UniqueKey<QuestionStatisticsRecord> PK_QUESTION_STATISTICS = UniqueKeys0.PK_QUESTION_STATISTICS;
	public static final org.jooq.UniqueKey<QuestionTypeRecord> PK_QUESTION_TYPE = UniqueKeys0.PK_QUESTION_TYPE;
	public static final org.jooq.UniqueKey<RolePrivsRecord> PK_ROLE_PRIVS = UniqueKeys0.PK_ROLE_PRIVS;
	public static final org.jooq.UniqueKey<RolesRecord> PK_ROLES = UniqueKeys0.PK_ROLES;
	public static final org.jooq.UniqueKey<ShadowRecord> PK_SHADOW = UniqueKeys0.PK_SHADOW;
	public static final org.jooq.UniqueKey<StudentRecord> PK_STUDENT = UniqueKeys0.PK_STUDENT;
	public static final org.jooq.UniqueKey<StudentResultRecord> PK_STUDENT_RESULT = UniqueKeys0.PK_STUDENT_RESULT;
	public static final org.jooq.UniqueKey<StudentStatisticsRecord> PK_STUDENT_STATISTICS = UniqueKeys0.PK_STUDENT_STATISTICS;
	public static final org.jooq.UniqueKey<StudentTaskRecord> PK_STUDENT_TASK = UniqueKeys0.PK_STUDENT_TASK;
	public static final org.jooq.UniqueKey<StudiesCourseRecord> PK_STUDIES_COURSE = UniqueKeys0.PK_STUDIES_COURSE;
	public static final org.jooq.UniqueKey<TaskAnswerRecord> PK_TASK_ANSWER = UniqueKeys0.PK_TASK_ANSWER;
	public static final org.jooq.UniqueKey<TaskQuestionsRecord> PK_TASK_QUESTIONS = UniqueKeys0.PK_TASK_QUESTIONS;
	public static final org.jooq.UniqueKey<ThemeRecord> PK_THEME = UniqueKeys0.PK_THEME;
	public static final org.jooq.UniqueKey<UserRolesRecord> PK_USER_ROLES = UniqueKeys0.PK_USER_ROLES;
	public static final org.jooq.UniqueKey<UsersRecord> PK_USERS = UniqueKeys0.PK_USERS;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<AnswerRecord, QuestionRecord> ANSWER__FK_ANSWER_QUESTION = ForeignKeys0.ANSWER__FK_ANSWER_QUESTION;
	public static final org.jooq.ForeignKey<EduGroupRecord, UsersRecord> EDU_GROUP__FK_EDU_GROUP_USERS = ForeignKeys0.EDU_GROUP__FK_EDU_GROUP_USERS;
	public static final org.jooq.ForeignKey<EduGroupCourseRecord, EduGroupRecord> EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_EDU_GROUP = ForeignKeys0.EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_EDU_GROUP;
	public static final org.jooq.ForeignKey<EduGroupCourseRecord, StudiesCourseRecord> EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_STUDIES_COURSE = ForeignKeys0.EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_STUDIES_COURSE;
	public static final org.jooq.ForeignKey<ExamRecord, EduGroupCourseRecord> EXAM__FK_EXAM_EDU_GROUP_COURSE = ForeignKeys0.EXAM__FK_EXAM_EDU_GROUP_COURSE;
	public static final org.jooq.ForeignKey<ExamRecord, UsersRecord> EXAM__FK_EXAM_USERS = ForeignKeys0.EXAM__FK_EXAM_USERS;
	public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ExamRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM = ForeignKeys0.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM;
	public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ThemeRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_THEME = ForeignKeys0.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_THEME;
	public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ExamRuleRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM_RULE = ForeignKeys0.EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM_RULE;
	public static final org.jooq.ForeignKey<ExaminationTicketRecord, ExamRecord> EXAMINATION_TICKET__FK_EXAMINATION_TICKET_EXAM = ForeignKeys0.EXAMINATION_TICKET__FK_EXAMINATION_TICKET_EXAM;
	public static final org.jooq.ForeignKey<LogsRecord, UsersRecord> LOGS__FK_LOGS_USERS = ForeignKeys0.LOGS__FK_LOGS_USERS;
	public static final org.jooq.ForeignKey<QuestionRecord, QuestionTypeRecord> QUESTION__FK_QUESTION_QUESTION_TYPE = ForeignKeys0.QUESTION__FK_QUESTION_QUESTION_TYPE;
	public static final org.jooq.ForeignKey<QuestionRecord, ThemeRecord> QUESTION__FK_QUESTION_THEME = ForeignKeys0.QUESTION__FK_QUESTION_THEME;
	public static final org.jooq.ForeignKey<QuestionStatisticsRecord, QuestionRecord> QUESTION_STATISTICS__FK_QUESTION_ID = ForeignKeys0.QUESTION_STATISTICS__FK_QUESTION_ID;
	public static final org.jooq.ForeignKey<RolePrivsRecord, RolesRecord> ROLE_PRIVS__FK_ROLE_PRIVS_ROLES = ForeignKeys0.ROLE_PRIVS__FK_ROLE_PRIVS_ROLES;
	public static final org.jooq.ForeignKey<RolePrivsRecord, PrivsRecord> ROLE_PRIVS__FK_ROLE_PRIVS_PRIVS = ForeignKeys0.ROLE_PRIVS__FK_ROLE_PRIVS_PRIVS;
	public static final org.jooq.ForeignKey<ShadowRecord, UsersRecord> SHADOW__FK_SHADOW_USERS = ForeignKeys0.SHADOW__FK_SHADOW_USERS;
	public static final org.jooq.ForeignKey<StudentRecord, UsersRecord> STUDENT__FK_STUDENT_PERSON = ForeignKeys0.STUDENT__FK_STUDENT_PERSON;
	public static final org.jooq.ForeignKey<StudentRecord, EduGroupRecord> STUDENT__FK_STUDENT_EDU_GROUP = ForeignKeys0.STUDENT__FK_STUDENT_EDU_GROUP;
	public static final org.jooq.ForeignKey<StudentStatisticsRecord, StudentRecord> STUDENT_STATISTICS__FK_STUDENT_ID = ForeignKeys0.STUDENT_STATISTICS__FK_STUDENT_ID;
	public static final org.jooq.ForeignKey<StudentTaskRecord, StudentRecord> STUDENT_TASK__FK_STUDENT_TASK_STUDENT = ForeignKeys0.STUDENT_TASK__FK_STUDENT_TASK_STUDENT;
	public static final org.jooq.ForeignKey<StudentTaskRecord, ExamRecord> STUDENT_TASK__FK_STUDENT_TASK_EXAM = ForeignKeys0.STUDENT_TASK__FK_STUDENT_TASK_EXAM;
	public static final org.jooq.ForeignKey<StudentTaskRecord, ExaminationTicketRecord> STUDENT_TASK__FK_STUDENT_TASK_EXAMINATION_TICKET = ForeignKeys0.STUDENT_TASK__FK_STUDENT_TASK_EXAMINATION_TICKET;
	public static final org.jooq.ForeignKey<StudentTaskRecord, StudentResultRecord> STUDENT_TASK__FK_STUDENT_TASK_STUDENT_RESULT = ForeignKeys0.STUDENT_TASK__FK_STUDENT_TASK_STUDENT_RESULT;
	public static final org.jooq.ForeignKey<TaskAnswerRecord, TaskQuestionsRecord> TASK_ANSWER__FK_TASK_ANSWER_TASK_QUESTIONS = ForeignKeys0.TASK_ANSWER__FK_TASK_ANSWER_TASK_QUESTIONS;
	public static final org.jooq.ForeignKey<TaskAnswerRecord, AnswerRecord> TASK_ANSWER__FK_TASK_ANSWER_ANSWER = ForeignKeys0.TASK_ANSWER__FK_TASK_ANSWER_ANSWER;
	public static final org.jooq.ForeignKey<TaskQuestionsRecord, StudentTaskRecord> TASK_QUESTIONS__FK_TASK_QUESTIONS_STUDENT_TASK = ForeignKeys0.TASK_QUESTIONS__FK_TASK_QUESTIONS_STUDENT_TASK;
	public static final org.jooq.ForeignKey<TaskQuestionsRecord, QuestionRecord> TASK_QUESTIONS__FK_TASK_QUESTIONS_QUESTION = ForeignKeys0.TASK_QUESTIONS__FK_TASK_QUESTIONS_QUESTION;
	public static final org.jooq.ForeignKey<ThemeRecord, ThemeRecord> THEME__FK_THEME_THEME = ForeignKeys0.THEME__FK_THEME_THEME;
	public static final org.jooq.ForeignKey<ThemeRecord, UsersRecord> THEME__FK_THEME_USER = ForeignKeys0.THEME__FK_THEME_USER;
	public static final org.jooq.ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__FK_USER_ROLES_USERS = ForeignKeys0.USER_ROLES__FK_USER_ROLES_USERS;
	public static final org.jooq.ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__FK_USER_ROLES_ROLES = ForeignKeys0.USER_ROLES__FK_USER_ROLES_ROLES;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<AnswerRecord> PK_ANSWER = createUniqueKey(Answer.ANSWER, Answer.ANSWER.ID);
		public static final org.jooq.UniqueKey<EduGroupRecord> PK_EDU_GROUP = createUniqueKey(EduGroup.EDU_GROUP, EduGroup.EDU_GROUP.ID);
		public static final org.jooq.UniqueKey<EduGroupCourseRecord> PK_EDU_GROUP_COURSE = createUniqueKey(EduGroupCourse.EDU_GROUP_COURSE, EduGroupCourse.EDU_GROUP_COURSE.ID);
		public static final org.jooq.UniqueKey<ExamRecord> PK_EXAM = createUniqueKey(Exam.EXAM, Exam.EXAM.ID);
		public static final org.jooq.UniqueKey<ExamRuleRecord> PK_EXAM_RULE = createUniqueKey(ExamRule.EXAM_RULE, ExamRule.EXAM_RULE.ID);
		public static final org.jooq.UniqueKey<ExamTreeNodeRecord> PK_EXAM_TREE_NODE = createUniqueKey(ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.EXAM_TREE_NODE.ID);
		public static final org.jooq.UniqueKey<ExaminationTicketRecord> PK_EXAMINATION_TICKET = createUniqueKey(ExaminationTicket.EXAMINATION_TICKET, ExaminationTicket.EXAMINATION_TICKET.ID);
		public static final org.jooq.UniqueKey<LogsRecord> PK_LOGS = createUniqueKey(Logs.LOGS, Logs.LOGS.USERNAME, Logs.LOGS.DOMAIN, Logs.LOGS.CREATED_AT);
		public static final org.jooq.UniqueKey<PrivsRecord> PK_PRIVS = createUniqueKey(Privs.PRIVS, Privs.PRIVS.ID);
		public static final org.jooq.UniqueKey<QuestionRecord> PK_QUESTION = createUniqueKey(Question.QUESTION, Question.QUESTION.ID);
		public static final org.jooq.UniqueKey<QuestionStatisticsRecord> PK_QUESTION_STATISTICS = createUniqueKey(QuestionStatistics.QUESTION_STATISTICS, QuestionStatistics.QUESTION_STATISTICS.ID);
		public static final org.jooq.UniqueKey<QuestionTypeRecord> PK_QUESTION_TYPE = createUniqueKey(QuestionType.QUESTION_TYPE, QuestionType.QUESTION_TYPE.ID);
		public static final org.jooq.UniqueKey<RolePrivsRecord> PK_ROLE_PRIVS = createUniqueKey(RolePrivs.ROLE_PRIVS, RolePrivs.ROLE_PRIVS.ROLENAME, RolePrivs.ROLE_PRIVS.PRIVILEGE_ID);
		public static final org.jooq.UniqueKey<RolesRecord> PK_ROLES = createUniqueKey(Roles.ROLES, Roles.ROLES.ROLENAME);
		public static final org.jooq.UniqueKey<ShadowRecord> PK_SHADOW = createUniqueKey(Shadow.SHADOW, Shadow.SHADOW.USERNAME);
		public static final org.jooq.UniqueKey<StudentRecord> PK_STUDENT = createUniqueKey(Student.STUDENT, Student.STUDENT.ID);
		public static final org.jooq.UniqueKey<StudentResultRecord> PK_STUDENT_RESULT = createUniqueKey(StudentResult.STUDENT_RESULT, StudentResult.STUDENT_RESULT.ID);
		public static final org.jooq.UniqueKey<StudentStatisticsRecord> PK_STUDENT_STATISTICS = createUniqueKey(StudentStatistics.STUDENT_STATISTICS, StudentStatistics.STUDENT_STATISTICS.ID);
		public static final org.jooq.UniqueKey<StudentTaskRecord> PK_STUDENT_TASK = createUniqueKey(StudentTask.STUDENT_TASK, StudentTask.STUDENT_TASK.ID);
		public static final org.jooq.UniqueKey<StudiesCourseRecord> PK_STUDIES_COURSE = createUniqueKey(StudiesCourse.STUDIES_COURSE, StudiesCourse.STUDIES_COURSE.ID);
		public static final org.jooq.UniqueKey<TaskAnswerRecord> PK_TASK_ANSWER = createUniqueKey(TaskAnswer.TASK_ANSWER, TaskAnswer.TASK_ANSWER.ID);
		public static final org.jooq.UniqueKey<TaskQuestionsRecord> PK_TASK_QUESTIONS = createUniqueKey(TaskQuestions.TASK_QUESTIONS, TaskQuestions.TASK_QUESTIONS.ID);
		public static final org.jooq.UniqueKey<ThemeRecord> PK_THEME = createUniqueKey(Theme.THEME, Theme.THEME.ID);
		public static final org.jooq.UniqueKey<UserRolesRecord> PK_USER_ROLES = createUniqueKey(UserRoles.USER_ROLES, UserRoles.USER_ROLES.USERNAME, UserRoles.USER_ROLES.ROLENAME);
		public static final org.jooq.UniqueKey<UsersRecord> PK_USERS = createUniqueKey(Users.USERS, Users.USERS.USERNAME);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<AnswerRecord, QuestionRecord> ANSWER__FK_ANSWER_QUESTION = createForeignKey(Keys.PK_QUESTION, Answer.ANSWER, Answer.ANSWER.QUESTION_ID);
		public static final org.jooq.ForeignKey<EduGroupRecord, UsersRecord> EDU_GROUP__FK_EDU_GROUP_USERS = createForeignKey(Keys.PK_USERS, EduGroup.EDU_GROUP, EduGroup.EDU_GROUP.INSTRUCTOR);
		public static final org.jooq.ForeignKey<EduGroupCourseRecord, EduGroupRecord> EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_EDU_GROUP = createForeignKey(Keys.PK_EDU_GROUP, EduGroupCourse.EDU_GROUP_COURSE, EduGroupCourse.EDU_GROUP_COURSE.EDU_GROUP_ID);
		public static final org.jooq.ForeignKey<EduGroupCourseRecord, StudiesCourseRecord> EDU_GROUP_COURSE__FK_EDU_GROUP_COURSE_STUDIES_COURSE = createForeignKey(Keys.PK_STUDIES_COURSE, EduGroupCourse.EDU_GROUP_COURSE, EduGroupCourse.EDU_GROUP_COURSE.STUDIES_COURSE_ID);
		public static final org.jooq.ForeignKey<ExamRecord, EduGroupCourseRecord> EXAM__FK_EXAM_EDU_GROUP_COURSE = createForeignKey(Keys.PK_EDU_GROUP_COURSE, Exam.EXAM, Exam.EXAM.EDU_GROUP_COURSE_ID);
		public static final org.jooq.ForeignKey<ExamRecord, UsersRecord> EXAM__FK_EXAM_USERS = createForeignKey(Keys.PK_USERS, Exam.EXAM, Exam.EXAM.EXAMENATOR_NAME);
		public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ExamRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM = createForeignKey(Keys.PK_EXAM, ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.EXAM_TREE_NODE.EXAM_ID);
		public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ThemeRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_THEME = createForeignKey(Keys.PK_THEME, ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.EXAM_TREE_NODE.THEME_ID);
		public static final org.jooq.ForeignKey<ExamTreeNodeRecord, ExamRuleRecord> EXAM_TREE_NODE__FK_EXAM_TREE_NODE_EXAM_RULE = createForeignKey(Keys.PK_EXAM_RULE, ExamTreeNode.EXAM_TREE_NODE, ExamTreeNode.EXAM_TREE_NODE.EXAM_RULE_ID);
		public static final org.jooq.ForeignKey<ExaminationTicketRecord, ExamRecord> EXAMINATION_TICKET__FK_EXAMINATION_TICKET_EXAM = createForeignKey(Keys.PK_EXAM, ExaminationTicket.EXAMINATION_TICKET, ExaminationTicket.EXAMINATION_TICKET.EXAM_ID);
		public static final org.jooq.ForeignKey<LogsRecord, UsersRecord> LOGS__FK_LOGS_USERS = createForeignKey(Keys.PK_USERS, Logs.LOGS, Logs.LOGS.USERNAME);
		public static final org.jooq.ForeignKey<QuestionRecord, QuestionTypeRecord> QUESTION__FK_QUESTION_QUESTION_TYPE = createForeignKey(Keys.PK_QUESTION_TYPE, Question.QUESTION, Question.QUESTION.QUESTION_TYPE_ID);
		public static final org.jooq.ForeignKey<QuestionRecord, ThemeRecord> QUESTION__FK_QUESTION_THEME = createForeignKey(Keys.PK_THEME, Question.QUESTION, Question.QUESTION.THEME_ID);
		public static final org.jooq.ForeignKey<QuestionStatisticsRecord, QuestionRecord> QUESTION_STATISTICS__FK_QUESTION_ID = createForeignKey(Keys.PK_QUESTION, QuestionStatistics.QUESTION_STATISTICS, QuestionStatistics.QUESTION_STATISTICS.QUESTION_ID);
		public static final org.jooq.ForeignKey<RolePrivsRecord, RolesRecord> ROLE_PRIVS__FK_ROLE_PRIVS_ROLES = createForeignKey(Keys.PK_ROLES, RolePrivs.ROLE_PRIVS, RolePrivs.ROLE_PRIVS.ROLENAME);
		public static final org.jooq.ForeignKey<RolePrivsRecord, PrivsRecord> ROLE_PRIVS__FK_ROLE_PRIVS_PRIVS = createForeignKey(Keys.PK_PRIVS, RolePrivs.ROLE_PRIVS, RolePrivs.ROLE_PRIVS.PRIVILEGE_ID);
		public static final org.jooq.ForeignKey<ShadowRecord, UsersRecord> SHADOW__FK_SHADOW_USERS = createForeignKey(Keys.PK_USERS, Shadow.SHADOW, Shadow.SHADOW.USERNAME);
		public static final org.jooq.ForeignKey<StudentRecord, UsersRecord> STUDENT__FK_STUDENT_PERSON = createForeignKey(Keys.PK_USERS, Student.STUDENT, Student.STUDENT.USERNAME);
		public static final org.jooq.ForeignKey<StudentRecord, EduGroupRecord> STUDENT__FK_STUDENT_EDU_GROUP = createForeignKey(Keys.PK_EDU_GROUP, Student.STUDENT, Student.STUDENT.EDU_GROUP_ID);
		public static final org.jooq.ForeignKey<StudentStatisticsRecord, StudentRecord> STUDENT_STATISTICS__FK_STUDENT_ID = createForeignKey(Keys.PK_STUDENT, StudentStatistics.STUDENT_STATISTICS, StudentStatistics.STUDENT_STATISTICS.STUDENT_ID);
		public static final org.jooq.ForeignKey<StudentTaskRecord, StudentRecord> STUDENT_TASK__FK_STUDENT_TASK_STUDENT = createForeignKey(Keys.PK_STUDENT, StudentTask.STUDENT_TASK, StudentTask.STUDENT_TASK.STUDENT_ID);
		public static final org.jooq.ForeignKey<StudentTaskRecord, ExamRecord> STUDENT_TASK__FK_STUDENT_TASK_EXAM = createForeignKey(Keys.PK_EXAM, StudentTask.STUDENT_TASK, StudentTask.STUDENT_TASK.EXAM_ID);
		public static final org.jooq.ForeignKey<StudentTaskRecord, ExaminationTicketRecord> STUDENT_TASK__FK_STUDENT_TASK_EXAMINATION_TICKET = createForeignKey(Keys.PK_EXAMINATION_TICKET, StudentTask.STUDENT_TASK, StudentTask.STUDENT_TASK.EXAMINATION_TICKET_ID);
		public static final org.jooq.ForeignKey<StudentTaskRecord, StudentResultRecord> STUDENT_TASK__FK_STUDENT_TASK_STUDENT_RESULT = createForeignKey(Keys.PK_STUDENT_RESULT, StudentTask.STUDENT_TASK, StudentTask.STUDENT_TASK.STUDENT_RESULT_ID);
		public static final org.jooq.ForeignKey<TaskAnswerRecord, TaskQuestionsRecord> TASK_ANSWER__FK_TASK_ANSWER_TASK_QUESTIONS = createForeignKey(Keys.PK_TASK_QUESTIONS, TaskAnswer.TASK_ANSWER, TaskAnswer.TASK_ANSWER.TASK_QUESTIONS_ID);
		public static final org.jooq.ForeignKey<TaskAnswerRecord, AnswerRecord> TASK_ANSWER__FK_TASK_ANSWER_ANSWER = createForeignKey(Keys.PK_ANSWER, TaskAnswer.TASK_ANSWER, TaskAnswer.TASK_ANSWER.ANSWER_ID);
		public static final org.jooq.ForeignKey<TaskQuestionsRecord, StudentTaskRecord> TASK_QUESTIONS__FK_TASK_QUESTIONS_STUDENT_TASK = createForeignKey(Keys.PK_STUDENT_TASK, TaskQuestions.TASK_QUESTIONS, TaskQuestions.TASK_QUESTIONS.STUDENT_TASK_ID);
		public static final org.jooq.ForeignKey<TaskQuestionsRecord, QuestionRecord> TASK_QUESTIONS__FK_TASK_QUESTIONS_QUESTION = createForeignKey(Keys.PK_QUESTION, TaskQuestions.TASK_QUESTIONS, TaskQuestions.TASK_QUESTIONS.QUESTION_ID);
		public static final org.jooq.ForeignKey<ThemeRecord, ThemeRecord> THEME__FK_THEME_THEME = createForeignKey(Keys.PK_THEME, Theme.THEME, Theme.THEME.PARENT);
		public static final org.jooq.ForeignKey<ThemeRecord, UsersRecord> THEME__FK_THEME_USER = createForeignKey(Keys.PK_USERS, Theme.THEME, Theme.THEME.CREATOR_NAME);
		public static final org.jooq.ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__FK_USER_ROLES_USERS = createForeignKey(Keys.PK_USERS, UserRoles.USER_ROLES, UserRoles.USER_ROLES.USERNAME);
		public static final org.jooq.ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__FK_USER_ROLES_ROLES = createForeignKey(Keys.PK_ROLES, UserRoles.USER_ROLES, UserRoles.USER_ROLES.ROLENAME);
	}
}
