/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db;

import ua.org.pius.studtrain.db.tables.*;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 777899383;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			Sequences.SEQ_PK_ANSWER,
			Sequences.SEQ_PK_EDU_GROUP,
			Sequences.SEQ_PK_EDU_GROUP_COURSE,
			Sequences.SEQ_PK_EXAM,
			Sequences.SEQ_PK_EXAM_RULE,
			Sequences.SEQ_PK_EXAM_TREE_NODE,
			Sequences.SEQ_PK_EXAMINATION_TICKET,
			Sequences.SEQ_PK_QUESTION,
			Sequences.SEQ_PK_QUESTION_STATISTICS,
			Sequences.SEQ_PK_QUESTION_TYPE,
			Sequences.SEQ_PK_STUDENT,
			Sequences.SEQ_PK_STUDENT_RESULT,
			Sequences.SEQ_PK_STUDENT_STATISTICS,
			Sequences.SEQ_PK_STUDENT_TASK,
			Sequences.SEQ_PK_STUDIES_COURSE,
			Sequences.SEQ_PK_TASK_ANSWER,
			Sequences.SEQ_PK_TASK_QUESTIONS,
			Sequences.SEQ_PK_THEME);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			Answer.ANSWER,
			EduGroup.EDU_GROUP,
			EduGroupCourse.EDU_GROUP_COURSE,
			Exam.EXAM,
			ExamRule.EXAM_RULE,
			ExamTreeNode.EXAM_TREE_NODE,
			ExaminationTicket.EXAMINATION_TICKET,
			Logs.LOGS,
			Privs.PRIVS,
			Question.QUESTION,
			QuestionStatistics.QUESTION_STATISTICS,
			QuestionType.QUESTION_TYPE,
			RolePrivs.ROLE_PRIVS,
			Roles.ROLES,
			Shadow.SHADOW,
			Student.STUDENT,
			StudentResult.STUDENT_RESULT,
			StudentStatistics.STUDENT_STATISTICS,
			StudentTask.STUDENT_TASK,
			StudiesCourse.STUDIES_COURSE,
			TaskAnswer.TASK_ANSWER,
			TaskQuestions.TASK_QUESTIONS,
			Theme.THEME,
			UserRoles.USER_ROLES,
			Users.USERS);
	}
}
