/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.seq_pk_answer</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_ANSWER = new org.jooq.impl.SequenceImpl<Long>("seq_pk_answer", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_edu_group</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EDU_GROUP = new org.jooq.impl.SequenceImpl<Long>("seq_pk_edu_group", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_edu_group_course</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EDU_GROUP_COURSE = new org.jooq.impl.SequenceImpl<Long>("seq_pk_edu_group_course", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_exam</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EXAM = new org.jooq.impl.SequenceImpl<Long>("seq_pk_exam", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_exam_rule</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EXAM_RULE = new org.jooq.impl.SequenceImpl<Long>("seq_pk_exam_rule", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_exam_tree_node</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EXAM_TREE_NODE = new org.jooq.impl.SequenceImpl<Long>("seq_pk_exam_tree_node", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_examination_ticket</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_EXAMINATION_TICKET = new org.jooq.impl.SequenceImpl<Long>("seq_pk_examination_ticket", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_question</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_QUESTION = new org.jooq.impl.SequenceImpl<Long>("seq_pk_question", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_question_statistics</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_QUESTION_STATISTICS = new org.jooq.impl.SequenceImpl<Long>("seq_pk_question_statistics", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_question_type</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_QUESTION_TYPE = new org.jooq.impl.SequenceImpl<Long>("seq_pk_question_type", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_student</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_STUDENT = new org.jooq.impl.SequenceImpl<Long>("seq_pk_student", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_student_result</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_STUDENT_RESULT = new org.jooq.impl.SequenceImpl<Long>("seq_pk_student_result", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_student_statistics</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_STUDENT_STATISTICS = new org.jooq.impl.SequenceImpl<Long>("seq_pk_student_statistics", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_student_task</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_STUDENT_TASK = new org.jooq.impl.SequenceImpl<Long>("seq_pk_student_task", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_studies_course</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_STUDIES_COURSE = new org.jooq.impl.SequenceImpl<Long>("seq_pk_studies_course", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_task_answer</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_TASK_ANSWER = new org.jooq.impl.SequenceImpl<Long>("seq_pk_task_answer", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_task_questions</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_TASK_QUESTIONS = new org.jooq.impl.SequenceImpl<Long>("seq_pk_task_questions", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.seq_pk_theme</code>
	 */
	public static final org.jooq.Sequence<Long> SEQ_PK_THEME = new org.jooq.impl.SequenceImpl<Long>("seq_pk_theme", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
