/**
 * This class is generated by jOOQ
 */
package ua.org.pius.studtrain.db;

import ua.org.pius.studtrain.db.tables.*;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.answer
	 */
	public static final Answer ANSWER = Answer.ANSWER;

	/**
	 * The table public.edu_group
	 */
	public static final EduGroup EDU_GROUP = EduGroup.EDU_GROUP;

	/**
	 * The table public.edu_group_course
	 */
	public static final EduGroupCourse EDU_GROUP_COURSE = EduGroupCourse.EDU_GROUP_COURSE;

	/**
	 * The table public.exam
	 */
	public static final Exam EXAM = Exam.EXAM;

	/**
	 * The table public.exam_rule
	 */
	public static final ExamRule EXAM_RULE = ExamRule.EXAM_RULE;

	/**
	 * The table public.exam_tree_node
	 */
	public static final ExamTreeNode EXAM_TREE_NODE = ExamTreeNode.EXAM_TREE_NODE;

	/**
	 * The table public.examination_ticket
	 */
	public static final ExaminationTicket EXAMINATION_TICKET = ExaminationTicket.EXAMINATION_TICKET;

	/**
	 * The table public.logs
	 */
	public static final Logs LOGS = Logs.LOGS;

	/**
	 * The table public.privs
	 */
	public static final Privs PRIVS = Privs.PRIVS;

	/**
	 * The table public.question
	 */
	public static final Question QUESTION = Question.QUESTION;

	/**
	 * The table public.question_statistics
	 */
	public static final QuestionStatistics QUESTION_STATISTICS = QuestionStatistics.QUESTION_STATISTICS;

	/**
	 * The table public.question_type
	 */
	public static final QuestionType QUESTION_TYPE = QuestionType.QUESTION_TYPE;

	/**
	 * The table public.role_privs
	 */
	public static final RolePrivs ROLE_PRIVS = RolePrivs.ROLE_PRIVS;

	/**
	 * The table public.roles
	 */
	public static final Roles ROLES = Roles.ROLES;

	/**
	 * The table public.shadow
	 */
	public static final Shadow SHADOW = Shadow.SHADOW;

	/**
	 * The table public.student
	 */
	public static final Student STUDENT = Student.STUDENT;

	/**
	 * The table public.student_result
	 */
	public static final StudentResult STUDENT_RESULT = StudentResult.STUDENT_RESULT;

	/**
	 * The table public.student_statistics
	 */
	public static final StudentStatistics STUDENT_STATISTICS = StudentStatistics.STUDENT_STATISTICS;

	/**
	 * The table public.student_task
	 */
	public static final StudentTask STUDENT_TASK = StudentTask.STUDENT_TASK;

	/**
	 * The table public.studies_course
	 */
	public static final StudiesCourse STUDIES_COURSE = StudiesCourse.STUDIES_COURSE;

	/**
	 * The table public.task_answer
	 */
	public static final TaskAnswer TASK_ANSWER = TaskAnswer.TASK_ANSWER;

	/**
	 * The table public.task_questions
	 */
	public static final TaskQuestions TASK_QUESTIONS = TaskQuestions.TASK_QUESTIONS;

	/**
	 * The table public.theme
	 */
	public static final Theme THEME = Theme.THEME;

	/**
	 * The table public.user_roles
	 */
	public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

	/**
	 * The table public.users
	 */
	public static final Users USERS = Users.USERS;
}
